import { AlertTriangle, ArrowDownRight, ArrowUpRight, Check, CircleDashed, Clock3, ShieldCheck } from "lucide-react";

import { AppShell } from "../../components/layout/app-shell";
import { governanceMetrics, pipelineStages, recentActions, riskDistribution } from "../../mock/dashboard";
import type { ActionStatus, PipelineState, RiskLevel } from "../../types/dashboard";
import { ActivityChart } from "./activity-chart";

const toneClasses = { neutral: "text-[var(--info)]", safe: "text-[var(--safe)]", warning: "text-[var(--warning)]", critical: "text-[var(--critical)]" };
const stateClasses: Record<PipelineState, string> = { completed: "border-[rgb(93_211_158/0.35)] bg-[rgb(93_211_158/0.08)] text-[var(--safe)]", processing: "border-[rgb(106_168_255/0.35)] bg-[rgb(106_168_255/0.08)] text-[var(--info)]", warning: "border-[rgb(237_138_76/0.35)] bg-[rgb(237_138_76/0.08)] text-[var(--high-risk)]", blocked: "border-[rgb(239_98_98/0.35)] bg-[rgb(239_98_98/0.08)] text-[var(--critical)]", "awaiting approval": "border-[rgb(231_183_91/0.35)] bg-[rgb(231_183_91/0.08)] text-[var(--warning)]", idle: "border-white/10 bg-white/[0.025] text-[var(--text-muted)]", failed: "border-[rgb(239_98_98/0.35)] text-[var(--critical)]" };
const riskClasses: Record<RiskLevel, string> = { Low: "text-[var(--safe)]", Medium: "text-[var(--warning)]", High: "text-[var(--high-risk)]", Critical: "text-[var(--critical)]" };
const statusClasses: Record<ActionStatus, string> = { Approved: "text-[var(--safe)]", Pending: "text-[var(--warning)]", Blocked: "text-[var(--critical)]", Executed: "text-[var(--info)]", Simulating: "text-[var(--intelligence)]" };

export function DashboardScreen() {
  return <AppShell><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--safe)]">Control plane / live</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Governance Overview</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Monitor governed AI activity, operational risk, policy enforcement, and controlled execution.</p></div><div className="flex items-center gap-2 rounded-[7px] border border-white/[0.08] bg-white/[0.025] px-3 py-2 text-xs text-[var(--text-muted)]"><Clock3 size={14} /> Updated just now</div></div>

    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Operational metrics">{governanceMetrics.map((metric, index) => <article key={metric.label} className="relative overflow-hidden rounded-[10px] border border-white/[0.08] bg-[var(--surface)] p-4"><div className="flex items-start justify-between"><p className="text-xs text-[var(--text-secondary)]">{metric.label}</p><span className={`text-[10px] ${toneClasses[metric.tone]}`}>{index === 2 ? <ArrowDownRight size={14} /> : <ArrowUpRight size={14} />}</span></div><div className="mt-4 flex items-end justify-between gap-3"><p className="text-3xl font-semibold tracking-[-0.04em]">{metric.value}</p><p className={`text-[10px] font-medium ${toneClasses[metric.tone]}`}>{metric.trend}</p></div><p className="mt-2 text-[10px] text-[var(--text-muted)]">{metric.context}</p><span className={`absolute bottom-0 left-0 h-px w-full bg-current opacity-40 ${toneClasses[metric.tone]}`} /></article>)}</section>

    <section className="mt-4 rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-medium">Active Governance Pipeline</p><p className="mt-1 font-mono text-[10px] text-[var(--text-muted)]">REQ-8F2A · destructive_data_operation</p></div><span className="rounded-full border border-[rgb(231_183_91/0.25)] bg-[rgb(231_183_91/0.07)] px-2.5 py-1 text-[10px] font-medium text-[var(--warning)]">AWAITING HUMAN APPROVAL</span></div>
      <div className="mt-6 grid gap-2 sm:grid-cols-4 xl:grid-cols-7">{pipelineStages.map((stage, index) => <div key={stage.label} className="relative"><div className={`min-h-[88px] rounded-[8px] border p-3 ${stateClasses[stage.state]}`}><div className="flex items-center justify-between"><span className="font-mono text-[9px] opacity-70">0{index + 1}</span>{stage.state === "completed" ? <Check size={14} /> : stage.state === "warning" ? <AlertTriangle size={14} /> : <CircleDashed size={14} />}</div><p className="mt-3 text-[10px] font-semibold uppercase tracking-[0.13em]">{stage.label}</p><p className="mt-1 text-[9px] opacity-70">{stage.detail}</p></div>{index < pipelineStages.length - 1 && <span className="signal-line absolute -right-2 top-1/2 z-10 hidden h-px w-2 xl:block" />}</div>)}</div>
    </section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.45fr_0.55fr]">
      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="mb-2 flex items-start justify-between"><div><h2 className="text-sm font-medium">Governed AI Activity</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Actions processed over the last 7 days</p></div><div className="text-right"><p className="text-xl font-semibold">1,208</p><p className="text-[9px] text-[var(--safe)]">+9.2% vs prior week</p></div></div><ActivityChart /></section>
      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Risk Distribution</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Current action exposure</p></div><ShieldCheck size={18} className="text-[var(--text-muted)]" /></div><div className="mt-7 flex h-2 overflow-hidden rounded-full">{Object.entries(riskDistribution).map(([risk, value]) => <span key={risk} style={{ width: `${value}%` }} className={{ Low: "bg-[var(--safe)]", Medium: "bg-[var(--warning)]", High: "bg-[var(--high-risk)]", Critical: "bg-[var(--critical)]" }[risk]} />)}</div><div className="mt-7 space-y-4">{Object.entries(riskDistribution).map(([risk, value]) => <div key={risk} className="flex items-center text-xs"><span className={`mr-2 size-1.5 rounded-full ${risk === "Low" ? "bg-[var(--safe)]" : risk === "Medium" ? "bg-[var(--warning)]" : risk === "High" ? "bg-[var(--high-risk)]" : "bg-[var(--critical)]"}`} /><span className="text-[var(--text-secondary)]">{risk}</span><span className="ml-auto font-mono text-[var(--text-muted)]">{value}%</span></div>)}</div></section>
    </div>

    <section className="mt-4 overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-medium">Recent AI Actions</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Latest requests entering the governance control plane</p></div><button className="text-xs text-[var(--text-secondary)] hover:text-white">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left"><thead><tr className="border-b border-white/[0.06] text-[9px] uppercase tracking-[0.12em] text-[var(--text-muted)]">{["Request ID", "Action", "Requested By", "Type", "Risk", "Policy Decision", "Status", "Time"].map((heading) => <th key={heading} className="px-4 py-3 font-medium first:pl-5 last:pr-5">{heading}</th>)}</tr></thead><tbody>{recentActions.map((action) => <tr key={action.id} className="border-b border-white/[0.05] last:border-0 hover:bg-white/[0.018]"><td className="px-4 py-3.5 pl-5 font-mono text-[10px] text-[var(--text-muted)]">{action.id}</td><td className="px-4 py-3.5 text-xs font-medium">{action.action}</td><td className="px-4 py-3.5 text-xs text-[var(--text-secondary)]">{action.requestedBy}</td><td className="px-4 py-3.5 font-mono text-[9px] text-[var(--text-muted)]">{action.type}</td><td className={`px-4 py-3.5 text-xs font-medium ${riskClasses[action.risk]}`}>{action.risk}</td><td className="px-4 py-3.5 text-xs text-[var(--text-secondary)]">{action.decision}</td><td className={`px-4 py-3.5 text-xs ${statusClasses[action.status]}`}>{action.status}</td><td className="px-4 py-3.5 pr-5 text-xs text-[var(--text-muted)]">{action.time}</td></tr>)}</tbody></table></div></section>
  </main></AppShell>;
}
