import { ArrowRight, Check, CheckCircle2, CircleDot, DatabaseBackup, LockKeyhole, RotateCcw, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { AppShell } from "../../components/layout/app-shell";
import { executionIdentity, executionMetrics, executionStages, operationScenario } from "../../mock/executions";

export function ExecutionsScreen() {
  return <AppShell pageTitle="Execution Monitor"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Controlled execution / completed preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Execution Monitor</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Trace authorization, recovery controls, resource changes, and verification through a governed execution lifecycle.</p></div><div className="flex items-center gap-2 text-xs text-[var(--safe)]"><CheckCircle2 size={15} />EXECUTION SUCCESSFUL</div></div>

    <section className="mt-7 overflow-hidden rounded-[12px] border border-[rgb(93_211_158/0.18)] bg-[var(--surface)]"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><p className="font-mono text-[10px] text-[var(--text-muted)]">RUN-8F2A-01 · REQ-8F2A</p><h2 className="mt-2 text-sm font-medium">{operationScenario.request}</h2></div><span className="rounded-[6px] border border-[rgb(93_211_158/0.22)] bg-[rgb(93_211_158/0.06)] px-2.5 py-1.5 text-[9px] font-medium text-[var(--safe)]">COMPLETED · 14.2s</span></div><div className="grid gap-px bg-white/[0.06] sm:grid-cols-3 xl:grid-cols-6">{executionMetrics.map((metric) => <div key={metric.label} className="bg-[var(--surface)] p-4"><p className="text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{metric.label}</p><p className={`mt-2 text-xl font-semibold ${metric.label === "Failed" ? "text-[var(--safe)]" : ""}`}>{metric.value}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">{metric.detail}</p></div>)}</div></section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.25fr_0.75fr]">
      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Execution Control Plane</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Deterministic Phase 1 lifecycle preview</p></div><ShieldCheck size={17} className="text-[var(--safe)]" /></div><ol className="mt-6">{executionStages.map((stage, index) => <li key={stage.label} className="relative grid grid-cols-[34px_1fr_auto] gap-3 pb-6 last:pb-0"><div className="relative z-10 grid size-7 place-items-center rounded-full border border-[rgb(93_211_158/0.28)] bg-[rgb(93_211_158/0.07)] text-[var(--safe)]"><Check size={12} /></div>{index < executionStages.length - 1 && <span className="absolute left-[13px] top-7 h-[calc(100%-28px)] w-px bg-[rgb(93_211_158/0.2)]" />}<div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-medium">{stage.label}</h3><span className="text-[8px] font-semibold text-[var(--safe)]">COMPLETE</span></div><p className="mt-1 text-[10px] text-[var(--text-muted)]">{stage.detail}</p></div><time className="font-mono text-[9px] text-[var(--text-muted)]">{stage.timestamp}</time></li>)}</ol></section>

      <aside className="space-y-4"><section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><CircleDot size={15} className="text-[var(--info)]" /><h2 className="text-sm font-medium">Execution Identity</h2></div><dl className="mt-5 space-y-3">{executionIdentity.map(([label,value]) => <div key={label} className="flex justify-between gap-4 border-b border-white/[0.05] pb-3 last:border-0"><dt className="text-[9px] text-[var(--text-muted)]">{label}</dt><dd className="text-right font-mono text-[9px] text-[var(--text-secondary)]">{value}</dd></div>)}</dl><div className="mt-5 flex items-center gap-2 rounded-[7px] border border-white/[0.07] bg-white/[0.02] p-3 text-[10px] text-[var(--text-secondary)]"><LockKeyhole size={14} className="text-[var(--safe)]" />Workspace lock released after verification</div></section>
        <section className="rounded-[12px] border border-[rgb(106_168_255/0.18)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><DatabaseBackup size={16} className="text-[var(--info)]" /><h2 className="text-sm font-medium">Recovery Snapshot Available</h2></div><p className="mt-2 font-mono text-xs text-[var(--info)]">SNP-8F2A-01</p><div className="mt-5 grid grid-cols-2 gap-4 text-[9px]"><div><p className="text-[var(--text-muted)]">Created</p><p className="mt-1 text-[var(--text-secondary)]">Before execution</p></div><div><p className="text-[var(--text-muted)]">Resources</p><p className="mt-1 text-[var(--text-secondary)]">143</p></div><div><p className="text-[var(--text-muted)]">Snapshot size</p><p className="mt-1 text-[var(--text-secondary)]">412 MB</p></div><div><p className="text-[var(--text-muted)]">Retention</p><p className="mt-1 text-[var(--text-secondary)]">30 days</p></div><div><p className="text-[var(--text-muted)]">Eligibility</p><p className="mt-1 text-[var(--safe)]">Rollback eligible</p></div><div><p className="text-[var(--text-muted)]">Integrity</p><p className="mt-1 text-[var(--text-secondary)]">Verified in preview</p></div></div><button disabled title="Rollback is not implemented in Phase 1" className="mt-5 flex w-full cursor-not-allowed items-center justify-center gap-2 rounded-[7px] border border-white/[0.08] px-4 py-2.5 text-xs text-[var(--text-muted)] opacity-70"><RotateCcw size={14} />Rollback · Preview only</button></section>
        <Link href="/audit" className="flex w-full items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-3 text-xs font-medium text-black hover:bg-zinc-200">View Audit Trail <ArrowRight size={14} /></Link></aside>
    </div>
  </main></AppShell>;
}
