import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { app } from "../src/app.js";
import { disconnectDatabase, getDatabase } from "../src/config/database.js";
import { buildPolicyContext, evaluatePolicyRules, resolvePolicyDecision } from "../src/services/policy/policyEngine.js";
import { POLICY_RULES } from "../src/services/policy/policyRules.js";
import { hashPassword } from "../src/utils/auth/password.js";
import { assertAuthConfiguration } from "../src/utils/auth/token.js";

const prefix = "phase6-"; const marker = "[phase6]"; const password = `Aa1!${randomUUID()}z`;
const identities = Object.fromEntries(["EMPLOYEE", "MANAGER", "ADMIN", "OTHER", "NORISK"].map((role) => [role, `${prefix}${role.toLowerCase()}-${randomUUID()}@shadowos.dev`]));
const cookies = {}; const contexts = {}; let baseUrl; let server;
async function api(path, options = {}) { const response = await fetch(`${baseUrl}${path}`, options); const body = await response.json(); assert.equal(JSON.stringify(body).includes("passwordHash"), false); return { response, body }; }
async function login(role) { const result = await api("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: identities[role], password }) }); return result.response.headers.get("set-cookie").split(";", 1)[0]; }
async function pipeline(role, prompt, withRisk = true) { const created = await api("/api/requests", { method: "POST", headers: { "content-type": "application/json", cookie: cookies[role] }, body: JSON.stringify({ prompt: `${marker} ${prompt}`, environment: "PRODUCTION" }) }); const plan = (await api(`/api/requests/${created.body.request.id}/plan`, { method: "POST", headers: { cookie: cookies[role] } })).body.plan; const simulation = (await api(`/api/requests/${created.body.request.id}/simulation`, { method: "POST", headers: { cookie: cookies[role] } })).body.simulation; const risk = withRisk ? (await api(`/api/requests/${created.body.request.id}/risk`, { method: "POST", headers: { cookie: cookies[role] } })).body.riskAssessment : null; return { request: created.body.request, plan, simulation, risk }; }
function evaluate(role, id, body) { return api(`/api/requests/${id}/policy`, { method: "POST", headers: { cookie: cookies[role], ...(body === undefined ? {} : { "content-type": "application/json" }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); }
async function cleanup() { await getDatabase().user.deleteMany({ where: { email: { startsWith: prefix } } }); }

before(async () => { assertAuthConfiguration(); await getDatabase().$connect(); await cleanup(); const passwordHash = await hashPassword(password); await getDatabase().user.createMany({ data: Object.entries(identities).map(([role, email]) => ({ name: `Phase 6 ${role}`, email, passwordHash, role: ["MANAGER", "ADMIN"].includes(role) ? role : "EMPLOYEE", status: "ACTIVE" })) }); server = app.listen(0, "127.0.0.1"); await new Promise((resolve, reject) => { server.once("listening", resolve); server.once("error", reject); }); baseUrl = `http://127.0.0.1:${server.address().port}`; for (const role of Object.keys(identities)) cookies[role] = await login(role); });
after(async () => { await cleanup(); if (server) await new Promise((resolve) => server.close(resolve)); await disconnectDatabase(); });

test("unauthenticated POST policy returns 401", async () => { const context = await pipeline("EMPLOYEE", "Archive inactive customer accounts older than 2 years"); assert.equal((await api(`/api/requests/${context.request.id}/policy`, { method: "POST" })).response.status, 401); contexts.EMPLOYEE = context; });
test("request without risk returns RISK_ASSESSMENT_REQUIRED", async () => { const context = await pipeline("NORISK", "Archive inactive customer accounts older than 2 years", false); const result = await evaluate("NORISK", context.request.id); assert.equal(result.response.status, 409); assert.equal(result.body.error.code, "RISK_ASSESSMENT_REQUIRED"); });
for (const role of ["EMPLOYEE", "MANAGER", "ADMIN"]) test(`${role} can evaluate own policy`, async () => { const context = role === "EMPLOYEE" ? contexts.EMPLOYEE : await pipeline(role, "Delete archived invoices older than January 2024"); const result = await evaluate(role, context.request.id); assert.equal(result.response.status, 201); contexts[role] = { ...context, policy: result.body.policyEvaluation }; });
test("archive evaluates ALLOW with only safe reversible rule", () => { const policy = contexts.EMPLOYEE.policy; assert.equal(policy.decision, "ALLOW"); assert.deepEqual(policy.matches.map((match) => match.ruleKey), ["safe-reversible-allow"]); assert.equal(policy.matches.some((match) => match.ruleKey === "production-destructive-approval"), false); });
test("delete evaluates BLOCK with explainable contributing rules", () => { const policy = contexts.MANAGER.policy; assert.equal(policy.decision, "BLOCK"); for (const key of ["critical-risk-block", "irreversible-mutation-approval", "production-destructive-approval"]) assert.ok(policy.matches.some((match) => match.ruleKey === key)); });
test("decision precedence is explicit", () => { assert.equal(resolvePolicyDecision([{ decision: "ALLOW" }, { decision: "REQUIRE_APPROVAL" }, { decision: "BLOCK" }]), "BLOCK"); assert.equal(resolvePolicyDecision([{ decision: "ALLOW" }, { decision: "REQUIRE_APPROVAL" }]), "REQUIRE_APPROVAL"); assert.equal(resolvePolicyDecision([{ decision: "ALLOW" }]), "ALLOW"); });
test("targeted HIGH, scope, dependency and safe contexts resolve deterministically", () => { const base = buildPolicyContext(contexts.EMPLOYEE); const high = evaluatePolicyRules({ ...base, risk: { ...base.risk, score: 60, level: "HIGH" } }); assert.equal(high.decision, "REQUIRE_APPROVAL"); const scope = evaluatePolicyRules({ ...base, simulation: { ...base.simulation, affectedResources: 50, dependencyObservations: 3 } }); assert.equal(scope.decision, "BLOCK"); });
test("rule priorities and counts are deterministic", () => { const policy = contexts.MANAGER.policy; assert.deepEqual(policy.matches.map((match) => match.priority), [...policy.matches.map((match) => match.priority)].sort((a, b) => b - a)); assert.equal(policy.evaluatedRuleCount, POLICY_RULES.length); assert.equal(policy.matchedRuleCount, policy.matches.length); });
test("repeated evaluation and GET are idempotent without duplicate matches", async () => { const repeated = await evaluate("MANAGER", contexts.MANAGER.request.id); assert.equal(repeated.body.policyEvaluation.id, contexts.MANAGER.policy.id); assert.equal(await getDatabase().policyEvaluation.count({ where: { riskAssessmentId: contexts.MANAGER.risk.id } }), 1); assert.equal(await getDatabase().policyMatch.count({ where: { policyEvaluationId: contexts.MANAGER.policy.id } }), contexts.MANAGER.policy.matchedRuleCount); const read = await api(`/api/requests/${contexts.MANAGER.request.id}/policy`, { headers: { cookie: cookies.MANAGER } }); assert.equal(read.response.status, 200); assert.equal(read.body.policyEvaluation.id, contexts.MANAGER.policy.id); });
test("cross-user POST and GET are concealed", async () => { assert.equal((await evaluate("OTHER", contexts.ADMIN.request.id)).response.status, 404); assert.equal((await api(`/api/requests/${contexts.ADMIN.request.id}/policy`, { headers: { cookie: cookies.OTHER } })).response.status, 404); });
test("injected server-controlled policy output is rejected", async () => { const context = await pipeline("OTHER", "Archive inactive customer accounts older than 2 years"); for (const body of [{ decision: "ALLOW" }, { matches: [] }, { ruleKey: "fake" }, { summary: "Injected" }, { priority: 100 }]) assert.equal((await evaluate("OTHER", context.request.id, body)).response.status, 400); assert.equal(await getDatabase().policyEvaluation.count({ where: { riskAssessmentId: context.risk.id } }), 0); });
test("malformed evidence fails safely", () => { const malformed = { ...contexts.ADMIN, simulation: { ...contexts.ADMIN.simulation, affectedResources: 99 } }; assert.throws(() => buildPolicyContext(malformed), (error) => error.code === "INVALID_POLICY_INPUT"); });
test("policy evaluation does not mutate upstream governance records", async () => { const request = await getDatabase().request.findUnique({ where: { id: contexts.ADMIN.request.id } }); const plan = await getDatabase().executionPlan.findUnique({ where: { id: contexts.ADMIN.plan.id } }); const simulation = await getDatabase().simulationRun.findUnique({ where: { id: contexts.ADMIN.simulation.id } }); const risk = await getDatabase().riskAssessment.findUnique({ where: { id: contexts.ADMIN.risk.id }, include: { factors: true } }); assert.equal(request.status, "PLANNED"); assert.equal(plan.status, "GENERATED"); assert.equal(simulation.status, "COMPLETED"); assert.equal(risk.score, 88); assert.equal(risk.factors.length, 6); });
test("repeat engine result is structurally equivalent", () => { const context = buildPolicyContext(contexts.ADMIN); assert.deepEqual(evaluatePolicyRules(context), evaluatePolicyRules(context)); });
test("temporary policy data is removed without touching manual evaluations", async () => { await cleanup(); assert.equal(await getDatabase().user.count({ where: { email: { startsWith: prefix } } }), 0); assert.equal(await getDatabase().request.count({ where: { prompt: { startsWith: marker } } }), 0); });
