import { ArrowRight, CircleAlert, FileCheck2, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { AppShell } from "../../components/layout/app-shell";
import { OperationContext } from "../../components/ui/operation-context";
import { operationScenario, policyCatalog, policyEvaluations, selectedPolicyLogic, snapshotPolicyLogic } from "../../mock/policies";
import type { PolicyOutcome, PolicyStatus } from "../../types/governance";

const outcomeStyle: Record<PolicyOutcome, string> = { PASSED: "text-[var(--safe)]", "APPROVAL REQUIRED": "text-[var(--warning)]", BLOCKED: "text-[var(--critical)]" };
const statusStyle: Record<PolicyStatus, string> = { Enabled: "text-[var(--safe)]", Draft: "text-[var(--warning)]", Disabled: "text-[var(--text-muted)]" };

export function PoliciesScreen() {
  return <AppShell pageTitle="Policy Engine"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--safe)]">Governance gate / policy evaluation</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Policy Engine</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Evaluate proposed AI operations against organizational governance rules before execution.</p></div><OperationContext scenario={operationScenario} /></div>

    <section className="mt-7 rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-medium">Active Policy Evaluation</h2><p className="mt-1 font-mono text-[10px] text-[var(--text-muted)]">{operationScenario.requestId} · {operationScenario.planVersion} · 4 policies evaluated</p></div><span className="flex items-center gap-2 text-xs font-medium text-[var(--warning)]"><CircleAlert size={14} />CONDITIONAL APPROVAL</span></div><div className="grid lg:grid-cols-[1.1fr_0.9fr]"><div className="divide-y divide-white/[0.055] border-b border-white/[0.07] lg:border-b-0 lg:border-r">{policyEvaluations.map((policy) => <article key={policy.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[1fr_auto] sm:px-5"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-medium">{policy.name}</h3><span className="font-mono text-[8px] text-[var(--text-muted)]">{policy.id}</span></div><p className="mt-2 text-[10px] text-[var(--text-muted)]">Evidence: {policy.evidence}</p></div><span className={`text-[9px] font-semibold tracking-wider ${outcomeStyle[policy.outcome]}`}>{policy.outcome}</span></article>)}</div><div className="p-4 sm:p-5"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Final decision</p><p className="mt-3 text-xl font-semibold text-[var(--warning)]">Conditional Approval</p><div className="mt-5 grid grid-cols-3 gap-px overflow-hidden rounded-[7px] border border-white/[0.07] bg-white/[0.07]">{[["3", "Passed", "text-[var(--safe)]"], ["1", "Approval", "text-[var(--warning)]"], ["0", "Blocked", "text-[var(--critical)]"]].map(([value,label,color]) => <div key={label} className="bg-[var(--surface)] p-3 text-center"><p className={`text-lg font-semibold ${color}`}>{value}</p><p className="mt-1 text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-[var(--text-secondary)]">Bulk destructive scope exceeds the autonomous execution threshold. A manager must review the available evidence.</p><Link href="/approvals" className="mt-5 flex w-full items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black hover:bg-zinc-200">Request Manager Approval <ArrowRight size={14} /></Link></div></div></section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.2fr_0.8fr]">
      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Policy Logic Evaluation</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Inspectable control-plane rules · read-only preview</p></div><FileCheck2 size={17} className="text-[var(--safe)]" /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{[["POL-BULK-DELETE-04", selectedPolicyLogic], ["POL-SNAPSHOT-01", snapshotPolicyLogic]].map(([id,logic]) => <article key={id as string} className="rounded-[9px] border border-white/[0.07] bg-[#0a0c0f] p-4"><p className="font-mono text-[9px] text-[var(--text-muted)]">{id as string}</p><div className="mt-4 space-y-2">{(logic as typeof selectedPolicyLogic).map(([operator,field,result]) => <div key={`${operator}-${field}`} className="grid grid-cols-[45px_1fr] gap-2 font-mono text-[10px]"><span className={operator === "THEN" ? "text-[var(--warning)]" : "text-[var(--intelligence)]"}>{operator}</span><span><span className="text-[var(--text-secondary)]">{field}</span> <span className="text-white">{result}</span></span></div>)}</div></article>)}</div>
      </section>
      <aside className="rounded-[12px] border border-[rgb(231_183_91/0.18)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><ShieldCheck size={16} className="text-[var(--warning)]" /><h2 className="text-sm font-medium">Evaluation Evidence</h2></div><p className="mt-2 font-mono text-[9px] text-[var(--text-muted)]">POL-BULK-DELETE-04</p><dl className="mt-5 space-y-3">{[["Category", "Destructive actions"], ["Scope", "Production"], ["Enforcement", "Approval gate"], ["Matched", "action.type = DELETE"], ["Evidence", "resource.count = 143"], ["Decision", "Require Manager Approval"], ["Approver", "Manager"]].map(([label,value]) => <div key={label} className="flex justify-between gap-4 border-b border-white/[0.05] pb-3 last:border-0"><dt className="text-[9px] text-[var(--text-muted)]">{label}</dt><dd className={`text-right font-mono text-[9px] ${label === "Decision" ? "text-[var(--warning)]" : "text-[var(--text-secondary)]"}`}>{value}</dd></div>)}</dl></aside>
    </div>

    <section className="mt-4 overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="border-b border-white/[0.07] px-4 py-4 sm:px-5"><h2 className="text-sm font-medium">Organizational Policy Catalog</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Configured governance controls · preview data</p></div><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left"><thead><tr className="border-b border-white/[0.06] text-[8px] uppercase tracking-[0.13em] text-[var(--text-muted)]">{["Policy","Category","Scope","Enforcement","Status","Last Updated"].map((heading) => <th key={heading} className="px-4 py-3 font-medium first:pl-5">{heading}</th>)}</tr></thead><tbody>{policyCatalog.map((policy) => <tr key={policy.id} className="border-b border-white/[0.05] last:border-0 hover:bg-white/[0.018]"><td className="px-4 py-3.5 pl-5"><p className="text-xs font-medium">{policy.name}</p><p className="mt-1 font-mono text-[8px] text-[var(--text-muted)]">{policy.id}</p></td><td className="px-4 py-3.5 text-[10px] text-[var(--text-secondary)]">{policy.category}</td><td className="px-4 py-3.5 text-[10px] text-[var(--text-secondary)]">{policy.scope}</td><td className="px-4 py-3.5 text-[10px] text-[var(--text-secondary)]">{policy.enforcement}</td><td className={`px-4 py-3.5 text-[10px] ${statusStyle[policy.status]}`}>{policy.status}</td><td className="px-4 py-3.5 text-[10px] text-[var(--text-muted)]">{policy.updated}</td></tr>)}</tbody></table></div></section>
  </main></AppShell>;
}
