import { ArrowDown, ArrowRight, Check, CircleDot, FileCode2, GitBranch, ShieldCheck } from "lucide-react";
import Link from "next/link";

import { AppShell } from "../../components/layout/app-shell";
import { OperationContext } from "../../components/ui/operation-context";
import { operationScenario, planActions, planInspector, validationChecks } from "../../mock/action-plans";

const actionStyles = { SEARCH: "border-[rgb(106_168_255/0.28)] border-l-[var(--info)] text-[var(--info)]", FILTER: "border-[rgb(167_139_250/0.28)] border-l-[var(--intelligence)] text-[var(--intelligence)]", DELETE: "border-[rgb(239_98_98/0.28)] border-l-[var(--critical)] bg-[rgb(239_98_98/0.018)] text-[var(--critical)]" };

export function ActionPlansScreen() {
  return <AppShell pageTitle="Action Plans"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Execution specification / {operationScenario.planVersion}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Action Plans</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Inspect the machine-generated operation graph, resolved targets, dependencies, and execution constraints.</p></div><span className="flex w-fit items-center gap-2 rounded-[7px] border border-[rgb(93_211_158/0.25)] bg-[rgb(93_211_158/0.06)] px-3 py-2 text-xs text-[var(--safe)]"><ShieldCheck size={14} />Structure valid · preview state</span></div>

    <section className="surface-panel mt-7 rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><OperationContext scenario={operationScenario} /><span className="font-mono text-[9px] uppercase tracking-[0.12em] text-[var(--text-muted)]">Generated 10:42:18 IST · Plan {operationScenario.planVersion}</span></div><div className="mt-5 border-t border-white/[0.06] pt-5"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Source request</p><p className="mt-2 text-lg tracking-[-0.015em]">“{operationScenario.request}”</p></div><div className="mt-5 grid gap-px overflow-hidden rounded-[8px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4">{[["Status", "Ready for simulation"], ["Actions", "3 sequential"], ["Impact", "143 resources · 384 MB"], ["Initial risk", "HIGH · 72/100"]].map(([label,value]) => <div key={label} className="bg-[var(--surface)] p-3.5"><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className={`mt-2 text-xs font-medium ${label === "Initial risk" ? "text-[var(--high-risk)]" : "text-white"}`}>{value}</p></div>)}</div></section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_0.65fr]">
      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Action Dependency Graph</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Deterministic sequence · dependencies locked</p></div><GitBranch size={17} className="text-[var(--text-muted)]" /></div><div className="mx-auto mt-7 max-w-2xl">{planActions.map((action, index) => <div key={action.type} className="relative pb-9 last:pb-0"><article className={`rounded-[9px] border border-l-2 bg-[#0b0d10] transition-[border-color,background-color] hover:bg-white/[0.018] ${actionStyles[action.type]}`}><div className="grid gap-4 p-4 sm:grid-cols-[52px_1fr_auto]"><div><p className="font-mono text-[9px] opacity-60">ACTION</p><p className="mt-1 font-mono text-lg tabular-nums">0{action.index}</p></div><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs font-semibold">{action.type}</span><span className="text-[var(--border-strong)]">/</span><span className="break-all font-mono text-[10px] text-[var(--text-secondary)]">{action.target}</span></div><p className="mt-3 rounded-[5px] border border-white/[0.06] bg-black/20 px-2.5 py-2 font-mono text-[10px] text-[var(--text-secondary)]">{action.argument}</p><div className="mt-4 grid gap-3 text-[10px] text-[var(--text-muted)] sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-[8px] uppercase tracking-wider">Dependency</p><p className="mt-1 text-[var(--text-secondary)]">{action.dependency}</p></div><div><p className="text-[8px] uppercase tracking-wider">Scope</p><p className="mt-1 text-[var(--text-secondary)]">{action.scope}</p></div><div><p className="text-[8px] uppercase tracking-wider">Requirement</p><p className={`mt-1 ${action.type === "DELETE" ? "text-[var(--warning)]" : "text-[var(--text-secondary)]"}`}>{action.requirement}</p></div><div><p className="text-[8px] uppercase tracking-wider">Reversible</p><p className="mt-1 text-[var(--safe)]">{action.reversible ? "Snapshot-backed" : "No"}</p></div></div></div><div className="text-left sm:text-right"><p className="font-mono text-xl font-semibold tabular-nums text-white">{action.affectedResources}</p><p className="text-[9px] text-[var(--text-muted)]">resources</p></div></div></article>{index < planActions.length - 1 && <div className="absolute bottom-1 left-1/2 flex -translate-x-1/2 flex-col items-center"><span className="h-5 w-px bg-white/15" /><ArrowDown size={13} className="text-[var(--text-muted)]" /></div>}</div>)}</div></section>

      <aside className="space-y-4"><section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><FileCode2 size={16} className="text-[var(--info)]" /><h2 className="text-sm font-medium">Plan Inspector</h2></div><dl className="mt-5 space-y-3">{planInspector.map(([label,value]) => <div key={label} className="flex items-start justify-between gap-4 border-b border-white/[0.05] pb-3 last:border-0 last:pb-0"><dt className="text-[10px] text-[var(--text-muted)]">{label}</dt><dd className="text-right font-mono text-[10px] text-[var(--text-secondary)]">{value}</dd></div>)}</dl></section><section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><CircleDot size={15} className="text-[var(--safe)]" /><h2 className="text-sm font-medium">Preview Validation</h2></div><p className="mt-2 text-[10px] leading-4 text-[var(--text-muted)]">Static Phase 1 validation state; no runtime engine is connected.</p><div className="mt-4 border-y border-white/[0.06]">{validationChecks.map((check, index) => <div key={check} className="grid grid-cols-[24px_1fr_auto] items-center gap-2 border-b border-white/[0.05] py-3 text-xs text-[var(--text-secondary)] last:border-0"><span className="grid size-5 place-items-center rounded-full bg-[rgb(93_211_158/0.08)] text-[var(--safe)]"><Check size={11} /></span><span>{check}</span><span className="font-mono text-[8px] text-[var(--safe)]">CHK-0{index + 1} / PASS</span></div>)}</div></section><Link href="/shadow-workspace" className="flex w-full items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-3 text-xs font-medium text-black transition-colors hover:bg-zinc-200">Run Safe Simulation <ArrowRight size={14} /></Link></aside>
    </div>
  </main></AppShell>;
}
