"use client";

import { ArrowRight, Bell, Check, CheckCheck, ChevronRight, CircleAlert, FileCheck2, PlayCircle, ShieldAlert } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { notificationItems } from "../../mock/notifications";
import type { NotificationCategory } from "../../types/insights";

const categoryIcon = { Approvals: CircleAlert, Risk: ShieldAlert, Execution: PlayCircle, Policy: FileCheck2, System: Bell };
const priorityStyle = { normal: "text-[var(--info)]", high: "text-[var(--warning)]", critical: "text-[var(--critical)]" };

export function NotificationsScreen() {
  const [filter, setFilter] = useState("All");
  const [items, setItems] = useState(notificationItems);
  const [selectedId, setSelectedId] = useState("NOT-001");
  const visible = useMemo(() => items.filter((item) => filter === "All" || filter === "Unread" && item.unread || item.category === filter), [filter, items]);
  const selected = items.find((item) => item.id === selectedId) ?? visible[0];
  const unread = items.filter((item) => item.unread).length;
  function toggleRead(id: string) { setItems((current) => current.map((item) => item.id === id ? { ...item, unread: !item.unread } : item)); }
  function markAllRead() { setItems((current) => current.map((item) => ({ ...item, unread: false }))); }
  return <AppShell pageTitle="Notifications"><main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--warning)]">Attention center / operational signals</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Notifications</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Review governance events that require attention or confirm important ShadowOS state changes.</p></div><button onClick={markAllRead} className="flex w-fit items-center gap-2 rounded-[7px] border border-white/[0.08] px-3 py-2 text-xs text-[var(--text-secondary)] hover:bg-white/[0.04]"><CheckCheck size={14} />Mark all read</button></div>
    <section className="surface-panel mt-7 grid grid-cols-2 gap-px overflow-hidden rounded-[10px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4">{[["Unread",unread],["Approval Required",2],["Critical",1],["System",2]].map(([label,value]) => <div key={label} className="bg-[var(--surface)] p-4"><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 font-mono text-2xl font-semibold tabular-nums">{value}</p></div>)}</section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[0.95fr_1.05fr]"><section className="surface-panel overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="border-b border-white/[0.07] p-3"><div className="flex flex-wrap gap-1" role="group" aria-label="Notification filters">{["All","Unread","Approvals","Risk","Execution","Policy","System"].map((item) => <button key={item} aria-pressed={filter === item} onClick={() => setFilter(item)} className={`rounded-[5px] px-2 py-1.5 text-[9px] transition-colors ${filter === item ? "bg-white/[0.09] text-white shadow-[inset_0_1px_rgb(255_255_255/0.03)]" : "text-[var(--text-muted)] hover:bg-white/[0.04]"}`}>{item}</button>)}</div></div><div>{visible.map((item) => { const Icon = categoryIcon[item.category as NotificationCategory]; const isSelected = selected?.id === item.id; return <button key={item.id} aria-pressed={isSelected} onClick={() => { setSelectedId(item.id); if (item.unread) toggleRead(item.id); }} className={`grid w-full grid-cols-[32px_minmax(0,1fr)_auto] gap-3 border-b border-l-2 border-white/[0.055] px-4 py-4 text-left transition-colors last:border-b-0 hover:bg-white/[0.02] ${isSelected ? "border-l-[var(--warning)] bg-white/[0.035]" : "border-l-transparent"} ${item.unread ? "text-white" : "text-[var(--text-secondary)]"}`}><span className={`relative grid size-8 place-items-center rounded-[7px] bg-white/[0.04] ${priorityStyle[item.priority]}`}><Icon size={15} />{item.unread && <i className="absolute -right-0.5 -top-0.5 size-2 rounded-full border border-[var(--surface)] bg-[var(--warning)]" />}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className={`text-xs ${item.unread ? "font-semibold" : "font-medium"}`}>{item.title}</p><span className="font-mono text-[8px] text-[var(--text-muted)]">{item.reference}</span>{item.unread && <span className="font-mono text-[7px] uppercase tracking-wider text-[var(--warning)]">Unread</span>}</div><p className="mt-1.5 text-[10px] text-[var(--text-secondary)]">{item.description}</p><p className="mt-1 truncate font-mono text-[9px] text-[var(--text-muted)]">{item.metadata}</p></div><div className="flex items-center gap-1 text-[9px] text-[var(--text-muted)]"><time>{item.timestamp}</time><ChevronRight size={12} /></div></button>})}{visible.length === 0 && <p className="p-10 text-center text-xs text-[var(--text-muted)]">No notifications in this view.</p>}</div></section>
      {selected ? <aside className="surface-panel h-fit rounded-[12px] border border-white/[0.08] bg-[var(--surface)] xl:sticky xl:top-20"><div className="border-b border-white/[0.07] p-4 sm:p-5"><div className="flex items-center justify-between"><span className={`font-mono text-[9px] font-medium uppercase tracking-wider ${priorityStyle[selected.priority]}`}>{selected.priority} priority · {selected.category}</span><button onClick={() => toggleRead(selected.id)} className="flex items-center gap-1.5 text-[9px] text-[var(--text-muted)] transition-colors hover:text-white"><Check size={11} />Mark {selected.unread ? "read" : "unread"}</button></div><h2 className="mt-4 text-xl font-semibold">{selected.title}</h2><p className="mt-2 text-sm text-[var(--text-secondary)]">{selected.description}</p></div><div className="p-4 sm:p-5"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Operational context</p><dl className="mt-4">{[["Reference",selected.reference],["Category",selected.category],["Priority",selected.priority],["Environment","Production"],["Actor",selected.category === "System" ? "ShadowOS Control Plane" : "Governance service (preview)"],["Timestamp",selected.timestamp],["Details",selected.metadata]].map(([label,value]) => <div key={label} className="grid grid-cols-[90px_minmax(0,1fr)] gap-3 border-b border-white/[0.05] py-3 first:pt-0 last:border-0 last:pb-0"><dt className="text-[9px] text-[var(--text-muted)]">{label}</dt><dd className="break-words text-right font-mono text-[9px] text-[var(--text-secondary)]">{value}</dd></div>)}</dl><p className="mt-5 text-[9px] leading-4 text-[var(--text-muted)]">Read state is local Phase 1 preview behavior and is not persisted.</p>{selected.href && <Link href={selected.href} className="mt-5 flex w-full items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black transition-colors hover:bg-zinc-200">Open Related Context <ArrowRight size={14} /></Link>}</div></aside> : null}</div>
  </main></AppShell>;
}
