"use client";

import { ArrowRight, Check, CheckCircle2, CircleAlert, MessageSquareText, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { approvalEvidence, approvalQueue, operationScenario } from "../../mock/approvals";

const riskStyle = { MEDIUM: "text-[var(--warning)]", HIGH: "text-[var(--high-risk)]", CRITICAL: "text-[var(--critical)]" };
type Decision = "idle" | "approved" | "rejected";

export function ApprovalsScreen() {
  const router = useRouter();
  const [filter, setFilter] = useState("All");
  const [decision, setDecision] = useState<Decision>("idle");
  const [comment, setComment] = useState("");
  const visibleQueue = approvalQueue.filter((item) => filter === "All" || filter === "High Risk" && item.risk === "HIGH" || filter === "Critical" && item.risk === "CRITICAL" || filter === "Assigned to Me" && item.assignee === "You");
  function approve() { setDecision("approved"); }
  return <AppShell pageTitle="Approval Center"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--warning)]">Human governance / decision required</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Approval Center</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Review operational evidence and make accountable decisions on consequential AI actions.</p></div>
    <div className="mt-7 grid gap-4 xl:grid-cols-[0.62fr_1.38fr]">
      <aside className="overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="border-b border-white/[0.07] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-medium">Approval Queue</h2><span className="font-mono text-[9px] text-[var(--text-muted)]">03 OPEN</span></div><div className="mt-4 flex flex-wrap gap-1" role="group" aria-label="Approval queue filters">{["All","High Risk","Critical","Assigned to Me"].map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-[5px] px-2 py-1.5 text-[9px] ${filter === item ? "bg-white/[0.09] text-white" : "text-[var(--text-muted)] hover:bg-white/[0.04]"}`}>{item}</button>)}</div></div><div className="divide-y divide-white/[0.055]">{visibleQueue.map((item) => <button key={item.requestId} className={`w-full px-4 py-4 text-left hover:bg-white/[0.025] ${item.requestId === operationScenario.requestId ? "border-l-2 border-[var(--warning)] bg-white/[0.018]" : "border-l-2 border-transparent"}`}><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-[var(--text-muted)]">{item.requestId}</span><span className={`text-[8px] font-semibold ${riskStyle[item.risk]}`}>{item.risk}</span></div><p className="mt-2 text-xs font-medium">{item.action}</p><div className="mt-3 flex items-center justify-between text-[9px] text-[var(--text-muted)]"><span>{item.state}</span><span>{item.assignee}</span></div></button>)}</div>{visibleQueue.length === 0 && <p className="p-8 text-center text-xs text-[var(--text-muted)]">No approvals match this filter.</p>}</aside>

      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><div className="flex items-center gap-2"><span className="font-mono text-[10px] text-[var(--text-muted)]">REQ-8F2A</span><span className="text-[8px] text-[var(--warning)]">AWAITING YOUR REVIEW</span></div><h2 className="mt-2 text-lg font-semibold">Delete archived invoices</h2></div><div className="text-right"><p className="text-2xl font-semibold">72 <span className="text-sm text-[var(--text-muted)]">/ 100</span></p><p className="mt-1 text-[9px] font-medium text-[var(--high-risk)]">HIGH RISK</p></div></div>
        <div className="grid lg:grid-cols-[1fr_0.82fr]"><div className="border-b border-white/[0.07] p-4 sm:p-5 lg:border-b-0 lg:border-r"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Original request</p><p className="mt-2 text-sm">“{operationScenario.request}”</p><div className="mt-5 grid gap-px overflow-hidden rounded-[7px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-3">{[["Requester", operationScenario.requestedBy], ["Environment", "Production"], ["Submitted", "15 Aug · 10:42 IST"], ["Plan", "v1.3 · 3 actions"], ["Simulation", "Complete · 2.4s"], ["Policy", "Conditional approval"]].map(([label,value]) => <div key={label} className="bg-[var(--surface)] p-3"><p className="text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 text-[10px] text-[var(--text-secondary)]">{value}</p></div>)}</div><div className="mt-5"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Risk explanation</p><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">Destructive bulk operation across 143 archived financial resources with 3 dependent workflows. Snapshot-based recovery reduces total exposure.</p></div><div className="mt-5 rounded-[8px] border border-[rgb(231_183_91/0.2)] bg-[rgb(231_183_91/0.04)] p-3"><p className="text-[9px] font-medium text-[var(--warning)]">Bulk Deletion Control · POL-BULK-DELETE-04</p><p className="mt-1 text-[10px] text-[var(--text-secondary)]">Manager approval required</p></div></div>
          <div className="p-4 sm:p-5"><h3 className="text-sm font-medium">Approval Evidence</h3><div className="mt-4 space-y-3">{approvalEvidence.map((evidence) => <div key={evidence.label} className="flex gap-3"><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-full ${evidence.state === "verified" ? "bg-[rgb(93_211_158/0.08)] text-[var(--safe)]" : "bg-[rgb(231_183_91/0.08)] text-[var(--warning)]"}`}>{evidence.state === "verified" ? <Check size={11} /> : <CircleAlert size={11} />}</span><div><p className="text-[10px] text-[var(--text-secondary)]">{evidence.label}</p><p className="mt-0.5 text-[9px] text-[var(--text-muted)]">{evidence.detail}</p></div></div>)}</div></div></div>
        <div className="border-t border-white/[0.07] p-4 sm:p-5">{decision === "idle" ? <><label htmlFor="approval-comment" className="flex items-center gap-2 text-[10px] text-[var(--text-muted)]"><MessageSquareText size={13} />Decision comment</label><textarea id="approval-comment" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Add decision context for the audit record…" className="mt-2 min-h-20 w-full resize-none rounded-[7px] border border-white/[0.09] bg-white/[0.02] p-3 text-xs outline-none placeholder:text-[var(--text-muted)] focus:border-[var(--focus)]" /><div className="mt-3 flex flex-col justify-end gap-2 sm:flex-row"><button onClick={() => setDecision("rejected")} className="inline-flex items-center justify-center gap-2 rounded-[7px] border border-[rgb(239_98_98/0.25)] px-4 py-2.5 text-xs text-[var(--critical)]"><X size={14} />Reject</button><button onClick={approve} className="inline-flex items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black"><CheckCircle2 size={14} />Approve Action</button></div><p className="mt-3 text-right text-[9px] text-[var(--text-muted)]">Frontend-only preview; decisions are not persisted.</p></> : <div className={`flex flex-col gap-4 rounded-[8px] border p-4 sm:flex-row sm:items-center sm:justify-between ${decision === "approved" ? "border-[rgb(93_211_158/0.2)] bg-[rgb(93_211_158/0.04)]" : "border-[rgb(239_98_98/0.2)] bg-[rgb(239_98_98/0.04)]"}`}><div><p className={`text-xs font-medium ${decision === "approved" ? "text-[var(--safe)]" : "text-[var(--critical)]"}`}>{decision === "approved" ? "Preview decision: Approved" : "Preview decision: Rejected"}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">Local UI state only · not persisted</p></div>{decision === "approved" ? <button onClick={() => router.push("/executions")} className="inline-flex items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black">Open Execution Monitor <ArrowRight size={14} /></button> : <button onClick={() => setDecision("idle")} className="text-xs text-[var(--text-secondary)]">Return to review</button>}</div>}</div>
      </section>
    </div>
  </main></AppShell>;
}
