"use client";

import { Check, ChevronRight, Filter, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { auditEvents, operationScenario } from "../../mock/audit";
import type { AuditEventType } from "../../types/governance";

const typeStyle: Record<AuditEventType, string> = { request: "bg-[var(--info)]", plan: "bg-[var(--intelligence)]", simulation: "bg-[var(--intelligence)]", risk: "bg-[var(--high-risk)]", policy: "bg-[var(--safe)]", approval: "bg-[var(--warning)]", execution: "bg-[var(--info)]", verification: "bg-[var(--safe)]", audit: "bg-[var(--safe)]" };

export function AuditScreen() {
  const [selectedId, setSelectedId] = useState("EVT-8F2A-009");
  const [eventType, setEventType] = useState("All events");
  const [query, setQuery] = useState("REQ-8F2A");
  const filtered = useMemo(() => auditEvents.filter((event) => (eventType === "All events" || event.type === eventType) && (event.requestId.toLowerCase().includes(query.toLowerCase()) || event.summary.toLowerCase().includes(query.toLowerCase()))), [eventType, query]);
  const selected = auditEvents.find((event) => event.id === selectedId) ?? filtered[0] ?? auditEvents[0];
  if (!selected) return null;
  return <AppShell pageTitle="Audit Logs"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--safe)]">Forensic trace / recorded preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Audit Logs</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Follow every governance decision and operational state transition across the complete request lifecycle.</p></div><div className="flex items-center gap-2 text-xs text-[var(--safe)]"><ShieldCheck size={15} />Integrity: Recorded</div></div>

    <section className="mt-7 flex flex-wrap items-center gap-2 rounded-[10px] border border-white/[0.08] bg-[var(--surface)] p-3"><label className="relative min-w-[220px] flex-1"><span className="sr-only">Request ID or event search</span><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 w-full rounded-[6px] border border-white/[0.08] bg-white/[0.02] pl-9 pr-3 font-mono text-[10px] outline-none focus:border-[var(--focus)]" placeholder="Request ID or event" /></label><label className="flex items-center gap-2 rounded-[6px] border border-white/[0.08] px-3"><Filter size={13} className="text-[var(--text-muted)]" /><span className="sr-only">Event type</span><select value={eventType} onChange={(event) => setEventType(event.target.value)} className="h-9 bg-transparent text-[10px] text-[var(--text-secondary)] outline-none"><option className="bg-[var(--surface)]">All events</option>{["request","plan","simulation","risk","policy","approval","execution","verification","audit"].map((type) => <option key={type} className="bg-[var(--surface)]" value={type}>{type}</option>)}</select></label>{[["Actor","All actors"],["Status","Recorded"],["Time range","Today"]].map(([label,value]) => <button key={label} className="h-9 rounded-[6px] border border-white/[0.08] px-3 text-left text-[9px] text-[var(--text-muted)]"><span className="mr-2">{label}:</span><span className="text-[var(--text-secondary)]">{value}</span></button>)}</section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.1fr_0.9fr]">
      <section className="overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-medium">Request Timeline</h2><p className="mt-1 font-mono text-[9px] text-[var(--text-muted)]">{operationScenario.requestId} · RUN-8F2A-01</p></div><span className="font-mono text-[9px] text-[var(--text-muted)]">{filtered.length} EVENTS</span></div><ol className="max-h-[780px] overflow-y-auto p-3 sm:p-4">{filtered.map((event, index) => <li key={event.id} className="relative"><button onClick={() => setSelectedId(event.id)} className={`grid w-full grid-cols-[24px_82px_1fr_auto] gap-2 rounded-[7px] px-2 py-3 text-left hover:bg-white/[0.025] sm:grid-cols-[24px_90px_1fr_auto] ${selected.id === event.id ? "bg-white/[0.04]" : ""}`}><div className="relative flex justify-center"><span className={`relative z-10 mt-1 size-2 rounded-full ${typeStyle[event.type]}`} />{index < filtered.length - 1 && <span className="absolute left-1/2 top-3 h-[calc(100%+12px)] w-px -translate-x-1/2 bg-white/[0.08]" />}</div><time className="font-mono text-[9px] text-[var(--text-muted)]">{event.timestamp}</time><div><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium">{event.summary}</p><span className="text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{event.type}</span></div><p className="mt-1 truncate text-[9px] text-[var(--text-muted)]">{event.actor} · {event.newState}</p></div><ChevronRight size={13} className="mt-0.5 text-[var(--text-muted)]" /></button></li>)}{filtered.length === 0 && <li className="p-10 text-center text-xs text-[var(--text-muted)]">No events match the selected filters.</li>}</ol></section>

      <aside className="h-fit rounded-[12px] border border-white/[0.08] bg-[var(--surface)] xl:sticky xl:top-20"><div className="border-b border-white/[0.07] px-4 py-4 sm:px-5"><div className="flex items-center justify-between"><span className="font-mono text-[9px] text-[var(--text-muted)]">{selected.id}</span><span className="flex items-center gap-1.5 text-[9px] text-[var(--safe)]"><Check size={11} />RECORDED</span></div><h2 className="mt-3 text-lg font-semibold">{selected.summary}</h2><p className="mt-2 text-xs text-[var(--text-secondary)]">{selected.actor}</p></div><div className="p-4 sm:p-5"><h3 className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Technical Inspector</h3><dl className="mt-4 space-y-3">{[["Timestamp", `15 Aug 2026 · ${selected.timestamp} IST`], ["Actor", selected.actor], ["Source", selected.source], ["Request ID", selected.requestId], ["Run ID", selected.runId ?? "Not assigned"], ["Plan version", "v1.3"], ["Environment", "Production"], ["Previous state", selected.previousState], ["New state", selected.newState], ["Integrity", "Recorded"]].map(([label,value]) => <div key={label} className="grid grid-cols-[100px_1fr] gap-3 border-b border-white/[0.05] pb-3 last:border-0"><dt className="text-[9px] text-[var(--text-muted)]">{label}</dt><dd className="text-right font-mono text-[9px] text-[var(--text-secondary)]">{value}</dd></div>)}</dl><h3 className="mt-6 text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Event Metadata</h3><div className="mt-3 rounded-[7px] border border-white/[0.07] bg-[#0a0c0f] p-3">{selected.metadata.map(([label,value]) => <div key={label} className="flex justify-between gap-4 py-1.5 font-mono text-[9px]"><span className="text-[var(--intelligence)]">{label}</span><span className="text-right text-[var(--text-secondary)]">{value}</span></div>)}</div><p className="mt-4 text-[9px] leading-4 text-[var(--text-muted)]">Phase 1 preview data. No persistence or cryptographic integrity mechanism is represented.</p></div></aside>
    </div>
  </main></AppShell>;
}
