"use client";

import { Activity, Bot, CheckCircle2, ChevronDown, FileCheck2, Search, ShieldAlert, UserCog } from "lucide-react";
import { useMemo, useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { activityItems } from "../../mock/activity";
import type { ActivityCategory } from "../../types/insights";

const toneStyle = { safe: "text-[var(--safe)] bg-[rgb(93_211_158/0.07)]", warning: "text-[var(--warning)] bg-[rgb(231_183_91/0.07)]", critical: "text-[var(--critical)] bg-[rgb(239_98_98/0.07)]", info: "text-[var(--info)] bg-[rgb(106_168_255/0.07)]", intelligence: "text-[var(--intelligence)] bg-[rgb(167_139_250/0.07)]" };
const categoryIcon = { "AI Operations": Bot, Governance: FileCheck2, Approvals: UserCog, Executions: CheckCircle2, Security: ShieldAlert };

export function ActivityScreen() {
  const [filter, setFilter] = useState("All Activity");
  const [query, setQuery] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);
  const visible = useMemo(() => activityItems.filter((item) => (filter === "All Activity" || item.category === filter) && `${item.title} ${item.description} ${item.requestId ?? ""}`.toLowerCase().includes(query.toLowerCase())), [filter, query]);
  return <AppShell pageTitle="Activity"><main className="mx-auto max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Organization stream / deterministic preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Activity</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Track governance decisions, AI operations, approvals, executions, policy events, and recovery activity across ShadowOS.</p></div>
    <section className="surface-panel mt-7 flex flex-col gap-3 rounded-[10px] border border-white/[0.08] bg-[var(--surface)] p-3"><div className="flex flex-wrap gap-1" role="group" aria-label="Activity categories">{["All Activity","AI Operations","Governance","Approvals","Executions","Security"].map((item) => <button key={item} aria-pressed={filter === item} onClick={() => setFilter(item)} className={`rounded-[5px] px-2.5 py-1.5 text-[9px] transition-colors ${filter === item ? "bg-white/[0.09] text-white shadow-[inset_0_1px_rgb(255_255_255/0.03)]" : "text-[var(--text-muted)] hover:bg-white/[0.04]"}`}>{item}</button>)}</div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search activity</span><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--text-muted)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search activity or request ID" className="h-9 w-full rounded-[6px] border border-white/[0.08] bg-white/[0.02] pl-9 pr-3 text-[10px] outline-none transition-colors focus:border-[var(--focus)]" /></label><button className="h-9 rounded-[6px] border border-white/[0.08] px-3 text-left text-[9px] text-[var(--text-muted)] transition-colors hover:bg-white/[0.025]">Actor: <span className="text-[var(--text-secondary)]">All</span></button></div></section>
    <section className="surface-panel mt-4 overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-4 sm:px-5"><div className="flex items-center gap-2"><Activity size={16} className="text-[var(--info)]" /><h2 className="text-sm font-medium">Organization Activity Stream</h2></div><span className="font-mono text-[9px] text-[var(--text-muted)]">{visible.length} EVENTS · DETERMINISTIC</span></div><ol>{visible.map((item) => { const Icon = categoryIcon[item.category as ActivityCategory]; const isExpanded = expanded === item.id; return <li key={item.id} className="border-b border-white/[0.055] last:border-0"><button onClick={() => setExpanded(isExpanded ? null : item.id)} aria-expanded={isExpanded} aria-controls={`activity-detail-${item.id}`} className={`grid w-full gap-3 border-l-2 px-4 py-4 text-left transition-colors hover:bg-white/[0.018] sm:grid-cols-[34px_minmax(0,1fr)_auto] sm:px-5 ${isExpanded ? "border-l-[var(--info)] bg-white/[0.025]" : "border-l-transparent"}`}><span className={`grid size-8 place-items-center rounded-[7px] ${toneStyle[item.tone]}`}><Icon size={15} /></span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-medium">{item.title}</h3><span className="font-mono text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{item.category}</span>{item.requestId && <span className="font-mono text-[8px] text-[var(--info)]">{item.requestId}</span>}</div><p className="mt-1.5 text-[10px] text-[var(--text-secondary)]">{item.description}</p><p className="mt-2 text-[9px] text-[var(--text-muted)]">Actor / {item.actor}</p>{isExpanded && <div id={`activity-detail-${item.id}`} className="mt-3 grid gap-2 border-l border-white/[0.08] pl-3 font-mono text-[9px] text-[var(--text-muted)] sm:grid-cols-3"><span>EVENT / {item.id}</span><span>ORIGIN / {item.category}</span><span>STATE / RECORDED PREVIEW</span></div>}</div><div className="flex items-center gap-2 text-[9px] text-[var(--text-muted)] sm:justify-end"><time>{item.timestamp}</time><ChevronDown size={12} className={`transition-transform ${isExpanded ? "rotate-180" : ""}`} /></div></button></li>})}{visible.length === 0 && <li className="p-12 text-center text-xs text-[var(--text-muted)]">No activity matches the selected filters.</li>}</ol></section>
  </main></AppShell>;
}
