"use client";

import { Bell, Bot, Building2, ChevronRight, CircleAlert, Code2, LockKeyhole, Plug, ShieldAlert, SlidersHorizontal, UserRound } from "lucide-react";
import { useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { aiSettings, approvalRules, futureIntegrations, notificationSettings, organizationSettings, profileSettings, riskThresholds, securitySettings, settingsSections } from "../../mock/settings";
import type { SettingsSection } from "../../types/insights";

const sectionIcon = { Organization: Building2, Profile: UserRound, "AI Configuration": Bot, Security: LockKeyhole, "Risk Thresholds": ShieldAlert, "Approval Rules": SlidersHorizontal, Notifications: Bell, Integrations: Plug };

function SettingRows({ rows }: { rows: ReadonlyArray<readonly [string, string]> }) { return <dl className="divide-y divide-white/[0.055]">{rows.map(([label,value]) => <div key={label} className="grid gap-2 py-4 sm:grid-cols-[1fr_1fr] sm:items-center"><dt className="text-xs text-[var(--text-secondary)]">{label}</dt><dd className="font-mono text-[10px] text-[var(--text-muted)] sm:text-right">{value}</dd></div>)}</dl>; }

export function SettingsScreen() {
  const [section, setSection] = useState<SettingsSection>("Organization");
  const [toggles, setToggles] = useState<Record<string, boolean>>(Object.fromEntries(notificationSettings.map((item) => [item, true])));
  return <AppShell pageTitle="Settings"><main className="mx-auto max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Control plane configuration</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Settings</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Configure organization-level ShadowOS preferences, governance defaults, and interface settings.</p></div>
    <div className="mt-7 grid gap-4 lg:grid-cols-[240px_1fr]"><nav aria-label="Settings sections" className="h-fit rounded-[10px] border border-white/[0.08] bg-[var(--surface)] p-2 lg:sticky lg:top-20">{settingsSections.map((item) => { const Icon = sectionIcon[item]; return <button key={item} onClick={() => setSection(item)} aria-current={section === item ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-[6px] px-3 py-2.5 text-left text-xs ${section === item ? "bg-white/[0.07] text-white" : "text-[var(--text-muted)] hover:bg-white/[0.03] hover:text-[var(--text-secondary)]"}`}><Icon size={15} /><span>{item}</span><ChevronRight size={12} className="ml-auto" /></button>})}<p className="px-3 pb-2 pt-4 text-[8px] leading-4 text-[var(--text-muted)]">Administrator preview · settings are not persisted.</p></nav>
      <section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="border-b border-white/[0.07] px-4 py-4 sm:px-6"><h2 className="text-lg font-semibold">{section}</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Phase 1 configuration preview · read-only unless noted</p></div><div className="px-4 sm:px-6">
        {section === "Organization" && <SettingRows rows={organizationSettings} />}
        {section === "Profile" && <SettingRows rows={profileSettings} />}
        {section === "AI Configuration" && <><SettingRows rows={aiSettings} /><div className="mb-5 flex gap-3 rounded-[8px] border border-[rgb(167_139_250/0.2)] bg-[rgb(167_139_250/0.04)] p-4"><Bot size={17} className="shrink-0 text-[var(--intelligence)]" /><div><p className="text-xs font-medium">AI produces proposals. AI does not execute operations.</p><p className="mt-1 text-[10px] leading-5 text-[var(--text-secondary)]">LLM output is validated against ShadowOS action schemas before entering the governance pipeline.</p><p className="mt-2 text-[9px] text-[var(--text-muted)]">Provider credentials are unavailable until the AI integration phase.</p></div></div></>}
        {section === "Security" && <><SettingRows rows={securitySettings} /><div className="mb-5 flex items-center gap-2 text-[9px] text-[var(--text-muted)]"><LockKeyhole size={13} />Preview only; no authentication or security policy is changed here.</div></>}
        {section === "Risk Thresholds" && <div className="py-5"><div className="grid gap-px overflow-hidden rounded-[8px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4">{riskThresholds.map(([label,range],index) => <div key={label} className="bg-[var(--surface)] p-4"><span className={`block h-1 w-8 rounded-full ${["bg-[var(--safe)]","bg-[var(--warning)]","bg-[var(--high-risk)]","bg-[var(--critical)]"][index]}`} /><p className="mt-4 text-xs font-medium">{label}</p><p className="mt-2 font-mono text-[10px] text-[var(--text-muted)]">{range}</p></div>)}</div><p className="mt-4 text-[9px] text-[var(--text-muted)]">Classification ranges are fixed and non-overlapping in this preview.</p></div>}
        {section === "Approval Rules" && <SettingRows rows={approvalRules} />}
        {section === "Notifications" && <div className="divide-y divide-white/[0.055]">{notificationSettings.map((item) => <div key={item} className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs text-[var(--text-secondary)]">{item}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">Interface notification preview</p></div><button role="switch" aria-checked={toggles[item]} aria-label={`${item} notifications`} onClick={() => setToggles((current) => ({ ...current, [item]: !current[item] }))} className={`relative h-5 w-9 rounded-full border transition-colors ${toggles[item] ? "border-[rgb(93_211_158/0.3)] bg-[rgb(93_211_158/0.18)]" : "border-white/10 bg-white/[0.04]"}`}><span className={`absolute top-0.5 size-3.5 rounded-full bg-white transition-transform ${toggles[item] ? "left-[18px]" : "left-0.5"}`} /></button></div>)}<p className="py-4 text-[9px] text-[var(--text-muted)]">Toggle state is local and not persisted.</p></div>}
        {section === "Integrations" && <div className="py-5"><div className="space-y-3">{futureIntegrations.map(([name,description]) => <article key={name} className="flex items-center gap-4 rounded-[8px] border border-white/[0.07] p-4"><span className="grid size-9 place-items-center rounded-[7px] bg-white/[0.04] text-[var(--text-muted)]">{name === "GitHub" ? <Code2 size={17} /> : <Plug size={17} />}</span><div><p className="text-xs font-medium">{name}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">{description}</p></div><span className="ml-auto text-[8px] font-medium uppercase tracking-wider text-[var(--text-muted)]">Coming Soon</span></article>)}</div><div className="mt-5 flex items-start gap-2 text-[9px] leading-4 text-[var(--text-muted)]"><CircleAlert size={13} className="mt-0.5 shrink-0" />No integrations are connected. OAuth and credentials are intentionally unavailable in Phase 1.</div></div>}
      </div></section></div>
  </main></AppShell>;
}
