"use client";

import { Bell, Bot, Building2, ChevronRight, CircleAlert, Code2, KeyRound, LockKeyhole, Plug, ShieldAlert, SlidersHorizontal, UserRound } from "lucide-react";
import { useMemo, useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { useAuth } from "../../hooks/use-auth";
import { roleLabel } from "../../lib/navigation";
import { aiSettings, approvalRules, futureIntegrations, notificationSettings, organizationSettings, riskThresholds, securitySettings, settingsSections as allSettingsSections } from "../../mock/settings";
import type { SettingsSection } from "../../types/insights";
import { AccessRolesSection } from "./access-roles-section";

const sectionIcon = { Organization: Building2, Profile: UserRound, "AI Configuration": Bot, Security: LockKeyhole, "Access & Roles": KeyRound, "Risk Thresholds": ShieldAlert, "Approval Rules": SlidersHorizontal, Notifications: Bell, Integrations: Plug };

function SettingRows({ rows }: { rows: ReadonlyArray<readonly [string, string]> }) { return <dl className="divide-y divide-white/[0.055]">{rows.map(([label,value]) => <div key={label} className="grid gap-2 py-4 transition-colors hover:bg-white/[0.012] sm:grid-cols-[1fr_1fr] sm:items-center"><dt className="text-xs text-[var(--text-secondary)]">{label}</dt><dd className={`font-mono text-[10px] sm:text-right ${label === "Direct LLM Execution" ? "font-semibold text-[var(--critical)]" : value.includes("Enabled") ? "text-[var(--safe)]" : "text-[var(--text-muted)]"}`}>{value}</dd></div>)}</dl>; }

export function SettingsScreen() {
  const { user } = useAuth();
  const [selectedSection, setSection] = useState<SettingsSection>("Profile");
  const [toggles, setToggles] = useState<Record<string, boolean>>(Object.fromEntries(notificationSettings.map((item) => [item, true])));
  const settingsSections = useMemo(() => user?.role === "ADMIN" ? allSettingsSections : allSettingsSections.filter((item) => item === "Profile" || item === "Notifications"), [user?.role]);
  const profileSettings = user ? [["Name", user.name], ["Role", `${roleLabel(user.role)} Â· read-only`], ["Email", user.email]] as const : [];
  const section = settingsSections.includes(selectedSection) ? selectedSection : "Profile";
  return <AppShell pageTitle="Settings"><main className="mx-auto max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Control plane configuration</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Settings</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Configure organization-level ShadowOS preferences, governance defaults, and interface settings.</p></div>
    <div className="mt-7 grid gap-4 lg:grid-cols-[240px_1fr]"><nav aria-label="Settings sections" className="surface-panel h-fit overflow-hidden rounded-[10px] border border-white/[0.08] bg-[var(--surface)] p-2 lg:sticky lg:top-20">{settingsSections.map((item, index) => { const Icon = sectionIcon[item]; const active = section === item; return <button key={item} onClick={() => setSection(item)} aria-current={active ? "page" : undefined} className={`relative flex w-full items-center gap-3 rounded-[6px] px-3 py-2.5 text-left text-xs transition-colors ${active ? "bg-white/[0.07] text-white shadow-[inset_0_1px_rgb(255_255_255/0.025)]" : "text-[var(--text-muted)] hover:bg-white/[0.03] hover:text-[var(--text-secondary)]"}`}>{active && <span className="absolute left-0 h-4 w-0.5 rounded-full bg-[var(--info)]" />}<span className="font-mono text-[8px] text-[var(--text-muted)]">0{index + 1}</span><Icon size={15} /><span>{item}</span><ChevronRight size={12} className="ml-auto" /></button>})}<p className="border-t border-white/[0.05] px-3 pb-2 pt-4 text-[8px] leading-4 text-[var(--text-muted)]">Authenticated identity · settings are not persisted.</p></nav>
      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex items-center justify-between gap-3 border-b border-white/[0.07] px-4 py-4 sm:px-6"><div><h2 className="text-lg font-semibold">{section}</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Phase 1 configuration preview · read-only unless noted</p></div><span className="hidden font-mono text-[8px] uppercase tracking-wider text-[var(--text-muted)] sm:block">Organization / Administrator</span></div><div className="px-4 sm:px-6">
        {section === "Organization" && <SettingRows rows={organizationSettings} />}
        {section === "Profile" && <><SettingRows rows={profileSettings} />{user?.roleRequest && <div className="mb-5 overflow-hidden rounded-[8px] border border-[rgb(231_183_91/0.2)] bg-[rgb(231_183_91/0.035)]"><div className="border-b border-[rgb(231_183_91/0.12)] px-4 py-3"><p className="text-[9px] font-medium uppercase tracking-[0.15em] text-[var(--warning)]">Account access</p></div><dl className="grid gap-px bg-white/[0.05] sm:grid-cols-3">{[["Current Role", roleLabel(user.role)], ["Requested Role", roleLabel(user.roleRequest.requestedRole)], ["Status", user.roleRequest.status === "PENDING" ? "Pending Approval" : "Request Rejected"]].map(([label, value]) => <div key={label} className="bg-[var(--surface)] p-4"><dt className="text-[9px] text-[var(--text-muted)]">{label}</dt><dd className="mt-2 text-xs font-medium text-[var(--text-secondary)]">{value}</dd></div>)}</dl>{user.roleRequest.status === "PENDING" && <p className="px-4 py-3 text-[9px] text-[var(--text-muted)]">Manager access requires administrator approval. Employee capabilities remain active while your request is reviewed.</p>}</div>}</>}
        {section === "AI Configuration" && <><SettingRows rows={aiSettings} /><div className="mb-5 grid overflow-hidden rounded-[8px] border border-[rgb(167_139_250/0.2)] bg-[rgb(167_139_250/0.035)] sm:grid-cols-[1fr_auto]"><div className="flex gap-3 p-4"><Bot size={17} className="shrink-0 text-[var(--intelligence)]" /><div><p className="text-xs font-medium">LLM proposes actions. ShadowOS governs them.</p><p className="mt-1 text-[10px] leading-5 text-[var(--text-secondary)]">LLM output is validated against ShadowOS action schemas before entering the governance pipeline.</p><p className="mt-2 text-[9px] text-[var(--text-muted)]">Google Gemini is planned; provider credentials remain unavailable until the AI integration phase.</p></div></div><div className="border-t border-[rgb(167_139_250/0.14)] bg-black/10 p-4 sm:border-l sm:border-t-0"><p className="font-mono text-[8px] uppercase tracking-wider text-[var(--text-muted)]">Direct execution</p><p className="mt-2 font-mono text-xs font-semibold text-[var(--critical)]">DISABLED</p><p className="mt-1 text-[8px] text-[var(--text-muted)]">Architecture boundary</p></div></div></>}
        {section === "Security" && <><SettingRows rows={securitySettings} /><div className="mb-5 flex items-center gap-2 text-[9px] text-[var(--text-muted)]"><LockKeyhole size={13} />Preview only; no authentication or security policy is changed here.</div></>}
        {section === "Access & Roles" && user?.role === "ADMIN" && <AccessRolesSection />}
        {section === "Risk Thresholds" && <div className="py-5"><div className="grid gap-px overflow-hidden rounded-[8px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4">{riskThresholds.map(([label,range],index) => <div key={label} className="bg-[var(--surface)] p-4"><span className={`block h-1 w-8 rounded-full ${["bg-[var(--safe)]","bg-[var(--warning)]","bg-[var(--high-risk)]","bg-[var(--critical)]"][index]}`} /><p className="mt-4 text-xs font-medium">{label}</p><p className="mt-2 font-mono text-[10px] text-[var(--text-muted)]">{range}</p></div>)}</div><p className="mt-4 text-[9px] text-[var(--text-muted)]">Classification ranges are fixed and non-overlapping in this preview.</p></div>}
        {section === "Approval Rules" && <SettingRows rows={approvalRules} />}
        {section === "Notifications" && <div className="divide-y divide-white/[0.055]">{notificationSettings.map((item) => <div key={item} className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs text-[var(--text-secondary)]">{item}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">Interface notification preview</p></div><button role="switch" aria-checked={toggles[item]} aria-label={`${item} notifications`} onClick={() => setToggles((current) => ({ ...current, [item]: !current[item] }))} className={`relative h-5 w-9 rounded-full border transition-colors ${toggles[item] ? "border-[rgb(93_211_158/0.3)] bg-[rgb(93_211_158/0.18)]" : "border-white/10 bg-white/[0.04]"}`}><span className={`absolute top-0.5 size-3.5 rounded-full bg-white transition-transform ${toggles[item] ? "left-[18px]" : "left-0.5"}`} /></button></div>)}<p className="py-4 text-[9px] text-[var(--text-muted)]">Toggle state is local and not persisted.</p></div>}
        {section === "Integrations" && <div className="py-5"><div className="divide-y divide-white/[0.055] border-y border-white/[0.055]">{futureIntegrations.map(([name,description]) => <article key={name} className="flex items-center gap-4 py-4 transition-colors hover:bg-white/[0.012]"><span className="grid size-9 place-items-center rounded-[7px] bg-white/[0.04] text-[var(--text-muted)]">{name === "GitHub" ? <Code2 size={17} /> : <Plug size={17} />}</span><div><p className="text-xs font-medium">{name}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">{description}</p></div><span className="ml-auto font-mono text-[8px] uppercase tracking-wider text-[var(--text-muted)]">Coming Soon</span></article>)}</div><div className="mt-5 flex items-start gap-2 text-[9px] leading-4 text-[var(--text-muted)]"><CircleAlert size={13} className="mt-0.5 shrink-0" />No integrations are connected. OAuth and credentials are intentionally unavailable in Phase 1.</div></div>}
      </div></section></div>
  </main></AppShell>;
}
