export const POLICY_THRESHOLDS = Object.freeze({ largeScopeApproval: 10, extremeScopeBlock: 50, dependencyApproval: 3 });

const rule = (key, name, description, priority, decision, evaluate, explain, observe) => Object.freeze({ key, name, description, priority, decision, evaluate, explain, observe });

export const POLICY_RULES = Object.freeze([
  rule("critical-risk-block", "Critical Risk Protection", "Blocks operations assessed as critical risk.", 100, "BLOCK", (c) => c.risk.level === "CRITICAL", () => "Critical-risk operations are blocked by the default governance policy.", (c) => ({ riskLevel: c.risk.level })),
  rule("extreme-scope-block", "Extreme Scope Protection", "Blocks exceptionally large projected changes.", 95, "BLOCK", (c) => c.simulation.affectedResources >= POLICY_THRESHOLDS.extremeScopeBlock, () => `Projected changes at or above ${POLICY_THRESHOLDS.extremeScopeBlock} are blocked.`, (c) => ({ affectedResources: c.simulation.affectedResources, threshold: POLICY_THRESHOLDS.extremeScopeBlock })),
  rule("high-risk-approval", "High Risk Approval", "Requires approval for high-risk operations.", 80, "REQUIRE_APPROVAL", (c) => c.risk.level === "HIGH", () => "High-risk operations require approval before continuation.", (c) => ({ riskLevel: c.risk.level })),
  rule("irreversible-mutation-approval", "Irreversible Mutation Approval", "Requires review for non-reversible mutations.", 75, "REQUIRE_APPROVAL", (c) => c.mutationActions.some((a) => !a.reversible), () => "A non-reversible mutation requires approval before continuation.", (c) => ({ irreversibleMutations: c.mutationActions.filter((a) => !a.reversible).length })),
  rule("production-destructive-approval", "Production Destructive Approval", "Requires review for destructive production mutations.", 70, "REQUIRE_APPROVAL", (c) => c.request.environment === "PRODUCTION" && c.mutationActions.some((a) => a.destructive), () => "A destructive mutation targeting Production requires approval.", (c) => ({ environment: c.request.environment, destructiveMutations: c.mutationActions.filter((a) => a.destructive).length })),
  rule("large-scope-approval", "Large Scope Protection", "Requires approval for broad projected changes.", 60, "REQUIRE_APPROVAL", (c) => c.simulation.affectedResources >= POLICY_THRESHOLDS.largeScopeApproval, () => `At least ${POLICY_THRESHOLDS.largeScopeApproval} projected changes require approval.`, (c) => ({ affectedResources: c.simulation.affectedResources, threshold: POLICY_THRESHOLDS.largeScopeApproval })),
  rule("dependency-exposure-approval", "Dependency Exposure Protection", "Requires approval for elevated dependency exposure.", 50, "REQUIRE_APPROVAL", (c) => c.simulation.dependencyObservations >= POLICY_THRESHOLDS.dependencyApproval, () => `At least ${POLICY_THRESHOLDS.dependencyApproval} dependency observations require approval.`, (c) => ({ dependencyObservations: c.simulation.dependencyObservations, threshold: POLICY_THRESHOLDS.dependencyApproval })),
  rule("safe-reversible-allow", "Safe Reversible Operation Allow", "Allows low-to-medium-risk reversible, non-destructive mutations.", 10, "ALLOW", (c) => ["LOW", "MEDIUM"].includes(c.risk.level) && c.mutationActions.length > 0 && c.mutationActions.every((a) => a.reversible && !a.destructive), () => "The operation is low-to-medium risk, non-destructive, and fully reversible.", (c) => ({ riskLevel: c.risk.level, mutationCount: c.mutationActions.length, allReversible: true, destructiveMutations: 0 })),
]);

export const POLICY_RULE_KEYS = POLICY_RULES.map((ruleDefinition) => ruleDefinition.key);
