"use client";

import { AlertTriangle, ArrowRight, Box, Check, File, Folder, GitCompareArrows, Link2, ShieldCheck, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { OperationContext } from "../../components/ui/operation-context";
import { operationScenario, resourceRows, simulationMetrics } from "../../mock/shadow-workspace";
import type { ResourceRow } from "../../types/operation";

type ViewMode = "Before" | "Difference" | "After";
const stateStyle: Record<ResourceRow["state"], string> = { unchanged: "text-[var(--text-muted)]", removed: "text-[var(--critical)] bg-[rgb(239_98_98/0.035)]", modified: "text-[var(--warning)] bg-[rgb(231_183_91/0.035)]", dependent: "text-[var(--intelligence)] bg-[rgb(167_139_250/0.035)]" };

export function ShadowWorkspaceScreen() {
  const [view, setView] = useState<ViewMode>("Difference");
  const visibleRows = view === "Before" ? resourceRows.filter((row) => row.state !== "dependent") : view === "After" ? resourceRows.filter((row) => row.state === "unchanged" || row.state === "dependent") : resourceRows;
  return <AppShell pageTitle="Shadow Workspace"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--intelligence)]">Isolated execution preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Shadow Workspace</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Evaluate proposed operations against an isolated representation before any production resource can be modified.</p></div><OperationContext scenario={operationScenario} /></div>

    <section className="surface-panel relative mt-7 flex flex-col gap-4 overflow-hidden rounded-[10px] border border-[rgb(167_139_250/0.28)] bg-[rgb(167_139_250/0.055)] p-4 sm:flex-row sm:items-center sm:justify-between"><span className="absolute inset-x-0 top-0 h-px bg-[var(--intelligence)] opacity-70" /><div className="flex items-start gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-[7px] border border-[rgb(167_139_250/0.24)] bg-[rgb(167_139_250/0.06)] text-[var(--intelligence)]"><ShieldCheck size={18} /></span><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[var(--intelligence)]">Simulation only — production has not been modified</p><p className="mt-1 text-xs text-[var(--text-secondary)]">Isolated snapshot SW-8F2A-01 · all proposed changes remain non-production.</p></div></div><div className="flex items-center gap-2 font-mono text-[10px] text-[var(--safe)]"><Check size={14} />SIMULATION_COMPLETE</div></section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_0.6fr]">
      <section className="surface-panel overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex flex-col gap-3 border-b border-white/[0.07] px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><h2 className="text-sm font-medium">Workspace State Comparison</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Finance / Invoices · snapshot SW-8F2A-01</p></div><div role="tablist" aria-label="Simulation view" className="flex w-fit rounded-[7px] border border-white/[0.08] bg-black/20 p-1">{(["Before", "Difference", "After"] as ViewMode[]).map((mode, index, modes) => <button key={mode} id={`simulation-tab-${mode.toLowerCase()}`} role="tab" aria-controls="simulation-workspace-panel" aria-selected={view === mode} tabIndex={view === mode ? 0 : -1} onClick={() => setView(mode)} onKeyDown={(event) => { if (event.key !== "ArrowLeft" && event.key !== "ArrowRight") return; event.preventDefault(); const offset = event.key === "ArrowRight" ? 1 : -1; const next = modes[(index + offset + modes.length) % modes.length]!; setView(next); requestAnimationFrame(() => document.getElementById(`simulation-tab-${next.toLowerCase()}`)?.focus()); }} className={`rounded-[5px] px-3 py-1.5 text-[10px] transition-[color,background-color] ${view === mode ? "bg-white/[0.1] text-white shadow-[inset_0_1px_rgb(255_255_255/0.04)]" : "text-[var(--text-muted)] hover:text-[var(--text-secondary)]"}`}>{mode}</button>)}</div></div>
        <div className="grid border-b border-white/[0.06] bg-white/[0.012] sm:grid-cols-2"><div className="border-b border-white/[0.06] px-4 py-3 sm:border-b-0 sm:border-r"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Current State</p><p className="mt-1 text-xs text-[var(--text-secondary)]">486 archived resources · 1.24 GB</p></div><div className="px-4 py-3"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--intelligence)]">Simulated State</p><p className="mt-1 text-xs text-[var(--text-secondary)]">343 archived resources · 856 MB</p></div></div>
        <div id="simulation-workspace-panel" role="tabpanel" aria-labelledby={`simulation-tab-${view.toLowerCase()}`} className="p-3 sm:p-4"><div className="mb-2 grid grid-cols-[1fr_auto] px-3 text-[8px] uppercase tracking-[0.14em] text-[var(--text-muted)]"><span>Resource tree</span><span>Preview state</span></div>{visibleRows.map((row, index) => { const Icon = row.kind === "folder" ? Folder : row.kind === "dependency" ? Link2 : row.kind === "group" ? Box : File; const depth = row.kind === "folder" && row.name === "Invoices/" ? 0 : row.kind === "folder" ? 1 : row.kind === "dependency" ? 1 : 2; return <div key={row.name} className={`group grid min-h-11 grid-cols-[minmax(0,1fr)_auto] items-center rounded-[6px] px-3 transition-colors hover:bg-white/[0.025] ${stateStyle[row.state]}`}><div className="flex min-w-0 items-center gap-2" style={{ paddingLeft: depth * 14 }}><span className="font-mono text-[9px] text-[var(--text-muted)]">{String(index + 1).padStart(2,"0")}</span><Icon size={14} className="shrink-0" /><span className={`truncate font-mono text-[10px] ${row.state === "unchanged" ? "text-[var(--text-secondary)]" : ""}`}>{row.name}</span></div><div className="ml-3 flex items-center gap-3"><span className="hidden max-w-44 truncate text-[9px] text-[var(--text-muted)] sm:block">{row.detail}</span><span className="w-16 text-right font-mono text-[8px] font-medium uppercase tracking-wider">{row.state}</span></div></div>})}</div>
      </section>

      <aside className="space-y-4"><section className="surface-panel rounded-[12px] border border-[rgb(239_98_98/0.2)] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between gap-2 text-[var(--critical)]"><div className="flex items-center gap-2"><Trash2 size={16} /><h2 className="text-sm font-medium">Proposed Difference</h2></div><span className="font-mono text-[8px] uppercase tracking-wider">Difference / destructive</span></div><div className="mt-6"><p className="text-[9px] uppercase tracking-[0.14em] text-[var(--critical)]">Removed in simulation</p><p className="mt-2 font-mono text-3xl font-semibold tracking-[-0.04em] tabular-nums">143</p><p className="mt-1 text-xs text-[var(--text-secondary)]">archived invoice files</p></div><div className="mt-5 grid grid-cols-2 gap-3 border-t border-white/[0.06] pt-4"><div><p className="text-[9px] text-[var(--text-muted)]">Storage reclaimed</p><p className="mt-1 font-mono text-sm font-medium tabular-nums">384 MB</p></div><div><p className="text-[9px] text-[var(--text-muted)]">Dependencies</p><p className="mt-1 font-mono text-sm font-medium tabular-nums text-[var(--warning)]">3 workflows</p></div></div></section><section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center gap-2"><GitCompareArrows size={16} className="text-[var(--intelligence)]" /><h2 className="text-sm font-medium">Simulation Summary</h2></div><div className="mt-5 grid gap-x-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">{simulationMetrics.map((metric) => <div key={metric.label} className="border-b border-white/[0.05] py-3 first:pt-0"><p className="text-[9px] text-[var(--text-muted)]">{metric.label}</p><p className="mt-1 font-mono text-sm font-semibold tabular-nums">{metric.value}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">{metric.detail}</p></div>)}</div></section><div className="rounded-[10px] border border-[rgb(231_183_91/0.2)] bg-[rgb(231_183_91/0.04)] p-4"><div className="flex gap-2"><AlertTriangle size={15} className="shrink-0 text-[var(--warning)]" /><p className="text-[10px] leading-5 text-[var(--text-secondary)]">Three workflows reference affected resources. Dependency impact must be evaluated before approval.</p></div></div><Link href="/risk" className="flex w-full items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-3 text-xs font-medium text-black transition-colors hover:bg-zinc-200">Analyze Risk <ArrowRight size={14} /></Link></aside>
    </div>
  </main></AppShell>;
}
