"use client";

import { ArrowDownRight, ArrowUpRight, ShieldCheck, TrendingDown } from "lucide-react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { AppShell } from "../../components/layout/app-shell";
import { analyticsMetrics, analyticsRiskDistribution, decisionDistribution, governanceActivity, policyEffectiveness, riskTrend } from "../../mock/analytics";

const metricTone = { info: "text-[var(--info)]", safe: "text-[var(--safe)]", critical: "text-[var(--critical)]", warning: "text-[var(--warning)]" };
const riskTone = { Low: "bg-[var(--safe)]", Medium: "bg-[var(--warning)]", High: "bg-[var(--high-risk)]", Critical: "bg-[var(--critical)]" };

export function AnalyticsScreen() {
  return <AppShell pageTitle="Analytics"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--info)]">Governance intelligence / 30 days</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Analytics</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Measure how ShadowOS governance reduces operational exposure across AI-generated actions.</p></div><span className="text-[9px] text-[var(--text-muted)]">PHASE 1 PREVIEW DATA · 17 JUL–15 AUG 2026</span></div>
    <section className="surface-panel mt-7 grid overflow-hidden rounded-[11px] border border-white/[0.08] bg-[var(--surface)] sm:grid-cols-2 xl:grid-cols-4">{analyticsMetrics.map((metric, index) => <article key={metric.label} className="relative min-h-[132px] border-b border-white/[0.07] p-4 transition-colors hover:bg-white/[0.015] sm:odd:border-r xl:border-b-0 xl:border-r xl:last:border-r-0"><div className="flex items-center justify-between"><p className="text-[11px] text-[var(--text-secondary)]">{metric.label}</p><span className={metricTone[metric.tone]}>{index === 3 ? <ArrowDownRight size={14} /> : <ArrowUpRight size={14} />}</span></div><p className="mt-4 font-mono text-3xl font-semibold tracking-[-0.04em] tabular-nums">{metric.value}</p><p className={`mt-2 text-[9px] ${metricTone[metric.tone]}`}>{metric.context}</p><span className={`absolute bottom-0 left-0 h-px w-full bg-current opacity-35 ${metricTone[metric.tone]}`} /></article>)}</section>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_0.6fr]"><section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-sm font-medium">Governance Activity</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Governed AI actions over the last 30 days</p></div><div className="flex gap-3 text-[8px] text-[var(--text-muted)]" aria-label="Chart legend"><span className="flex items-center gap-1"><i className="size-1.5 rounded-full bg-[var(--info)]" />Governed</span><span className="flex items-center gap-1"><i className="size-1.5 rounded-full bg-[var(--safe)]" />Approved</span><span className="flex items-center gap-1"><i className="size-1.5 rounded-full bg-[var(--critical)]" />Blocked</span></div></div><div className="mt-5 h-[260px]" role="img" aria-label="Line chart showing governed actions rising from 31 to 73, approved actions rising from 24 to 59, and blocked actions remaining between 2 and 5 over 30 days"><ResponsiveContainer width="100%" height="100%"><LineChart data={governanceActivity} margin={{ left: -26, right: 8 }}><CartesianGrid stroke="rgb(255 255 255 / 0.055)" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="day" tick={{ fill: "#707985", fontSize: 9 }} axisLine={false} tickLine={false} dy={6} /><YAxis tick={{ fill: "#707985", fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: "#13161a", border: "1px solid #252a31", borderRadius: 7, fontSize: 11, boxShadow: "0 14px 40px rgb(0 0 0 / 35%)" }} cursor={{ stroke: "#343b45" }} /><Line name="Governed" type="monotone" dataKey="total" stroke="#6aa8ff" strokeWidth={1.8} dot={false} /><Line name="Approved" type="monotone" dataKey="approved" stroke="#5dd39e" strokeWidth={1.5} dot={false} /><Line name="Blocked" type="monotone" dataKey="blocked" stroke="#ef6262" strokeWidth={1.5} dot={false} /></LineChart></ResponsiveContainer></div></section>
      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Risk Exposure Trend</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Organizational AI risk</p></div><TrendingDown size={16} className="text-[var(--safe)]" /></div><div className="mt-6 flex items-end gap-2"><p className="font-mono text-4xl font-semibold tabular-nums">34</p><p className="pb-1 text-sm text-[var(--text-muted)]">/ 100</p></div><p className="mt-2 text-[10px] text-[var(--warning)]">MEDIUM <span className="text-[var(--safe)]">· −8 pts over 30 days</span></p><div className="mt-7 space-y-4">{riskTrend.map((week) => <div key={week.week} className="grid grid-cols-[48px_1fr_24px] items-center gap-3"><span className="text-[9px] text-[var(--text-muted)]">{week.week}</span><div className="h-1.5 overflow-hidden rounded-full bg-white/[0.05]"><span className="block h-full bg-[var(--warning)]" style={{ width: `${week.value}%` }} /></div><span className="font-mono text-[9px] tabular-nums text-[var(--text-secondary)]">{week.value}</span></div>)}</div><div className="mt-7 border-t border-white/[0.06] pt-4 text-[10px] leading-5 text-[var(--text-muted)]">Risk exposure has declined each week while governed action volume increased.</div></section></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.35fr_0.65fr]"><section className="surface-panel overflow-hidden rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="border-b border-white/[0.07] px-4 py-4 sm:px-5"><h2 className="text-sm font-medium">Policy Effectiveness</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">How governance rules influence execution outcomes</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-white/[0.06] text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{["Policy","Evaluations","Triggered","Blocked","Approval Gates","Effectiveness"].map((h) => <th key={h} className="px-4 py-3 font-medium first:pl-5">{h}</th>)}</tr></thead><tbody>{policyEffectiveness.map((row) => <tr key={row.policy} className="border-b border-white/[0.05] transition-colors last:border-0 hover:bg-white/[0.018]"><td className="px-4 py-3.5 pl-5 text-xs">{row.policy}</td><td className="px-4 font-mono text-[10px] tabular-nums text-[var(--text-secondary)]">{row.evaluations}</td><td className="px-4 font-mono text-[10px] tabular-nums text-[var(--warning)]">{row.triggered}</td><td className="px-4 font-mono text-[10px] tabular-nums text-[var(--critical)]">{row.blocked}</td><td className="px-4 font-mono text-[10px] tabular-nums text-[var(--text-secondary)]">{row.approvalGates}</td><td className="px-4 text-[10px] text-[var(--safe)]">{row.effectiveness}</td></tr>)}</tbody></table></div></section>
      <div className="space-y-4"><section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><h2 className="text-sm font-medium">Approval Decisions</h2><div className="mt-5 flex h-2 overflow-hidden rounded-full">{decisionDistribution.map((item,index) => <span key={item.label} style={{ width: `${item.value}%` }} className={["bg-[var(--safe)]","bg-[var(--critical)]","bg-[var(--warning)]","bg-[var(--text-muted)]"][index]} />)}</div><div className="mt-5 grid grid-cols-2 gap-3">{decisionDistribution.map((item) => <div key={item.label}><p className="text-lg font-semibold">{item.value}%</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">{item.label}</p></div>)}</div></section><section className="rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><h2 className="text-sm font-medium">Risk Distribution</h2><div className="mt-5 space-y-3">{analyticsRiskDistribution.map((item) => <div key={item.label} className="grid grid-cols-[52px_1fr_26px] items-center gap-2"><span className="text-[9px] text-[var(--text-muted)]">{item.label}</span><div className="h-1.5 rounded-full bg-white/[0.05]"><span className={`block h-full rounded-full ${riskTone[item.label]}`} style={{ width: `${item.value}%` }} /></div><span className="font-mono text-[9px]">{item.value}%</span></div>)}</div></section></div></div>
    <section className="mt-4 flex items-start gap-3 rounded-[10px] border border-[rgb(93_211_158/0.18)] bg-[rgb(93_211_158/0.04)] p-4"><ShieldCheck size={17} className="mt-0.5 shrink-0 text-[var(--safe)]" /><div><p className="text-xs font-medium">Governance Insight</p><p className="mt-1 text-[10px] leading-5 text-[var(--text-secondary)]">Governance reduced high-risk production exposure by 21% compared with the previous 30-day period.</p><p className="mt-1 text-[8px] text-[var(--text-muted)]">Deterministic Phase 1 preview; not derived from production telemetry.</p></div></section>
  </main></AppShell>;
}
