import { ArrowRight, CheckCircle2, LockKeyhole, ShieldAlert, Undo2 } from "lucide-react";
import Link from "next/link";

import { AppShell } from "../../components/layout/app-shell";
import { OperationContext } from "../../components/ui/operation-context";
import { operationScenario, riskFactors, riskScale } from "../../mock/risk";

export function RiskScreen() {
  const total = riskFactors.reduce((sum, factor) => sum + factor.contribution, 0);
  return <AppShell pageTitle="Risk Engine"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--high-risk)]">Explainable assessment / preview</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">Risk Engine</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Understand the operational exposure behind a proposed AI action before policy and approval gates.</p></div><OperationContext scenario={operationScenario} /></div>

    <div className="mt-7 grid gap-4 xl:grid-cols-[0.65fr_1.35fr]">
      <section className="surface-panel rounded-[12px] border border-[rgb(237_138_76/0.22)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-[0.16em] text-[var(--text-muted)]">Composite risk score</span><span className="rounded-full border border-white/[0.08] px-2 py-1 font-mono text-[8px] text-[var(--text-muted)]">6 OBSERVED FACTORS</span></div><div className="mt-8 flex items-end gap-3"><span className="font-mono text-7xl font-semibold tracking-[-0.07em] tabular-nums">{operationScenario.riskScore}</span><span className="pb-2 text-xl text-[var(--text-muted)]">/ 100</span></div><div className="mt-3 flex items-center gap-2 text-sm font-semibold text-[var(--high-risk)]"><ShieldAlert size={17} />HIGH RISK <span className="font-mono text-[9px] font-normal text-[var(--text-muted)]">COMPUTED / EXPLAINABLE</span></div>
        <div className="relative mt-9"><div className="flex h-2 overflow-hidden rounded-full opacity-80"><span className="w-[30%] bg-[var(--safe)]" /><span className="w-[20%] bg-[var(--warning)]" /><span className="w-[25%] bg-[var(--high-risk)]" /><span className="w-[25%] bg-[var(--critical)]" /></div><span className="absolute -top-2 h-6 w-px bg-white" style={{ left: `${operationScenario.riskScore}%` }}><span className="absolute -left-1 top-0 size-2 rounded-full bg-white" /><span className="absolute -left-3.5 -top-6 font-mono text-[8px] text-white">72</span></span><div className="mt-3 grid grid-cols-4 gap-1">{riskScale.map((range) => <div key={range.label}><p className="text-[8px] font-medium text-[var(--text-secondary)]">{range.label}</p><p className="mt-0.5 font-mono text-[8px] text-[var(--text-muted)]">{range.range}</p></div>)}</div></div>
        <div className="mt-8 border-t border-white/[0.06] pt-5"><p className="text-[10px] uppercase tracking-[0.14em] text-[var(--text-muted)]">Risk explanation</p><p className="mt-3 text-sm leading-6 text-[var(--text-secondary)]">This request is classified as <strong className="font-medium text-[var(--high-risk)]">HIGH RISK</strong> because it performs a destructive bulk operation across 143 archived financial resources and affects 3 dependent workflows. Snapshot-based rollback reduces total exposure.</p></div>
      </section>

      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-medium">Risk Composition</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Observed condition → contribution → rationale</p></div><span className={`font-mono text-xs ${total === operationScenario.riskScore ? "text-[var(--safe)]" : "text-[var(--critical)]"}`}>TOTAL {total > 0 ? "+" : ""}{total} / VERIFIED</span></div><div>{riskFactors.map((factor, index) => <article key={factor.name} className="group grid gap-3 border-b border-white/[0.055] px-4 py-4 transition-colors last:border-0 hover:bg-white/[0.018] sm:grid-cols-[24px_1fr_90px] sm:px-5"><span className="font-mono text-[9px] text-[var(--text-muted)]">F{String(index + 1).padStart(2, "0")}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-xs font-medium">{factor.name}</h3><span className="text-[var(--border-strong)]">→</span><span className="rounded-[4px] border border-white/[0.06] bg-white/[0.018] px-1.5 py-0.5 font-mono text-[9px] text-[var(--text-secondary)]">{factor.observed}</span></div><p className="mt-2 max-w-2xl text-[10px] leading-4 text-[var(--text-muted)]">{factor.rationale}</p></div><div className="flex items-center gap-3 sm:justify-end"><span className={`font-mono text-sm font-semibold tabular-nums ${factor.contribution < 0 ? "text-[var(--safe)]" : "text-[var(--high-risk)]"}`}>{factor.contribution > 0 ? "+" : ""}{factor.contribution}</span><div className="h-1.5 w-12 overflow-hidden rounded-full bg-white/[0.05]"><span className={`block h-full ${factor.contribution < 0 ? "bg-[var(--safe)]" : "bg-[var(--high-risk)]"}`} style={{ width: `${Math.min(Math.abs(factor.contribution) / 30 * 100, 100)}%` }} /></div></div></article>)}</div></section>
    </div>

    <div className="mt-4 grid gap-4 lg:grid-cols-[1.15fr_0.85fr]"><section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><h2 className="text-sm font-medium">Observed Context</h2><div className="mt-5 grid gap-px overflow-hidden rounded-[8px] border border-white/[0.07] bg-white/[0.07] sm:grid-cols-4">{[["Operation", "DELETE", "Destructive"], ["Scope", "143 resources", "Bulk"], ["Environment", "Production", "Protected"], ["Reversibility", "Snapshot", "Recoverable"]].map(([label,value,note]) => <div key={label} className="bg-[var(--surface)] p-3.5"><p className="text-[8px] uppercase tracking-wider text-[var(--text-muted)]">{label}</p><p className="mt-2 font-mono text-[10px] text-white">{value}</p><p className="mt-2 text-[9px] text-[var(--text-muted)]">{note}</p></div>)}</div><div className="mt-4 flex items-center gap-2 text-[10px] text-[var(--safe)]"><Undo2 size={14} />Snapshot-backed recovery reduces the score by 8 points.</div></section>
      <section className="rounded-[12px] border border-[rgb(231_183_91/0.22)] bg-[rgb(231_183_91/0.045)] p-4 sm:p-5"><div className="flex items-center gap-2 text-[var(--warning)]"><LockKeyhole size={16} /><p className="text-[10px] font-medium uppercase tracking-[0.14em]">Recommended Decision</p></div><h2 className="mt-4 text-xl font-semibold tracking-[-0.02em]">Require Manager Approval</h2><p className="mt-2 text-xs leading-5 text-[var(--text-secondary)]">Bulk destructive action exceeds the autonomous execution threshold.</p><div className="mt-5 flex flex-col gap-3 border-t border-white/[0.07] pt-4 sm:flex-row sm:items-center sm:justify-between"><span className="flex items-center gap-2 text-[10px] text-[var(--safe)]"><CheckCircle2 size={13} />Recommendation ready</span><Link href="/policies" className="inline-flex items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black hover:bg-zinc-200">Evaluate Policies <ArrowRight size={14} /></Link></div></section></div>
  </main></AppShell>;
}
