"use client";

import { ArrowRight, Check, ChevronRight, CircleDot, FileClock, Plus, RotateCcw, ShieldAlert, Sparkles } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

import { AppShell } from "../../components/layout/app-shell";
import { OperationContext } from "../../components/ui/operation-context";
import { commandStages, operationScenario, planActions } from "../../mock/command-center";

const actionTone = { SEARCH: "text-[var(--info)] border-[rgb(106_168_255/0.25)]", FILTER: "text-[var(--intelligence)] border-[rgb(167_139_250/0.25)]", DELETE: "text-[var(--critical)] border-[rgb(239_98_98/0.25)]" };

export function CommandCenterScreen() {
  const [request, setRequest] = useState(`${operationScenario.request}.`);
  return <AppShell pageTitle="AI Command Center"><main className="mx-auto max-w-[1600px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-[var(--intelligence)]">AI operations / intake</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.035em]">AI Command Center</h1><p className="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">Convert natural-language operations into inspectable, governed execution plans before production access is considered.</p></div><div className="flex gap-2"><button className="flex items-center gap-2 rounded-[7px] border border-white/[0.08] px-3 py-2 text-xs text-[var(--text-secondary)] hover:bg-white/[0.04]"><FileClock size={14} />History</button><button onClick={() => setRequest("")} className="flex items-center gap-2 rounded-[7px] bg-white px-3 py-2 text-xs font-medium text-black hover:bg-zinc-200"><Plus size={14} />New request</button></div></div>

    <section className="surface-panel mt-7 overflow-hidden rounded-[12px] border border-white/[0.09] bg-[var(--surface)] shadow-[var(--shadow-panel)]">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.07] bg-white/[0.012] px-4 py-3 sm:px-5"><div className="flex items-center gap-3 text-xs"><span className="size-1.5 rounded-full bg-[var(--warning)]" /><span className="text-[var(--text-secondary)]">Production environment</span><span className="hidden font-mono text-[9px] uppercase tracking-[0.12em] text-[var(--text-muted)] sm:inline">Governed intake channel</span></div><OperationContext scenario={operationScenario} /></div>
      <div className="p-4 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-2"><div><label htmlFor="operation-request" className="text-[10px] font-medium uppercase tracking-[0.15em] text-[var(--text-muted)]">Operational intent</label><p className="mt-1 text-[10px] text-[var(--text-muted)]">Submit an operation for governed interpretation. This is not an execution command.</p></div><span className="font-mono text-[9px] text-[var(--text-muted)]">INTAKE / {operationScenario.requestId}</span></div><textarea id="operation-request" value={request} onChange={(event) => setRequest(event.target.value)} className="mt-4 min-h-28 w-full resize-none border-0 bg-transparent text-xl leading-8 tracking-[-0.02em] text-white outline-none placeholder:text-[var(--text-muted)] sm:text-2xl" placeholder="Describe the operation to govern…" /><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/[0.06] pt-4"><div className="flex flex-wrap gap-2"><span className="rounded-[5px] border border-white/[0.08] bg-white/[0.025] px-2.5 py-1.5 font-mono text-[9px] text-[var(--text-muted)]">SCOPE / FINANCE</span><span className="rounded-[5px] border border-white/[0.08] bg-white/[0.025] px-2.5 py-1.5 font-mono text-[9px] text-[var(--text-muted)]">MODE / PLAN_ONLY</span><span className="rounded-[5px] border border-white/[0.08] bg-white/[0.025] px-2.5 py-1.5 font-mono text-[9px] text-[var(--text-muted)]">PROVIDER / PLANNED</span></div><button type="button" className="flex items-center gap-2 rounded-[7px] border border-[rgb(167_139_250/0.3)] bg-[rgb(167_139_250/0.08)] px-3.5 py-2 text-xs font-medium text-[var(--intelligence)] transition-colors hover:bg-[rgb(167_139_250/0.12)]"><Sparkles size={14} />Interpret request</button></div></div>
    </section>

    <div className="mt-4 grid gap-4 xl:grid-cols-[0.72fr_1.28fr]">
      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-medium">Interpretation State</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">Deterministic Phase 1 UI preview</p></div><RotateCcw size={15} className="text-[var(--text-muted)]" /></div><div className="mt-5 border-y border-white/[0.06]">{commandStages.map((stage, index) => <div key={stage.label} className="relative grid grid-cols-[28px_1fr_auto] items-center gap-3 border-b border-white/[0.05] px-1 py-3.5 last:border-0"><span className={`grid size-6 place-items-center rounded-full border ${stage.state === "ready" ? "border-[rgb(167_139_250/0.35)] bg-[rgb(167_139_250/0.08)] text-[var(--intelligence)]" : "border-[rgb(93_211_158/0.3)] bg-[rgb(93_211_158/0.07)] text-[var(--safe)]"}`}>{stage.state === "ready" ? <CircleDot size={12} /> : <Check size={12} />}</span><div><p className="text-xs text-[var(--text-secondary)]">{stage.label}</p><p className="mt-0.5 font-mono text-[9px] text-[var(--text-muted)]">STAGE 0{index + 1} / {stage.state === "ready" ? "REVIEW_READY" : "COMPLETE"}</p></div><span className="font-mono text-[9px] text-[var(--text-muted)]">{index === 0 ? "INTENT" : index === 1 ? "03 OPS" : index === 2 ? "143 RES" : "PLAN v1.3"}</span>{index < commandStages.length - 1 && <span className="absolute bottom-[-8px] left-[15px] z-10 h-4 w-px bg-white/15" />}</div>)}</div><div className="mt-4"><p className="text-xs leading-5 text-[var(--text-muted)]">No operation has been executed. This preview represents a proposed governance plan only.</p></div></section>

      <section className="surface-panel rounded-[12px] border border-white/[0.08] bg-[var(--surface)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><h2 className="text-sm font-medium">Structured Plan Preview</h2><p className="mt-1 text-[10px] text-[var(--text-muted)]">{operationScenario.actionCount} actions detected · dependency order resolved</p></div><span className="font-mono text-[10px] text-[var(--text-muted)]">PLAN {operationScenario.planVersion}</span></div><div className="p-4 sm:p-5">{planActions.map((action, index) => <div key={action.type} className="group relative grid gap-3 border-b border-white/[0.06] py-4 first:pt-0 last:border-0 last:pb-0 sm:grid-cols-[54px_1fr_auto]"><span className={`flex h-7 w-12 items-center justify-center rounded-[5px] border font-mono text-[9px] font-semibold transition-colors group-hover:bg-white/[0.025] ${actionTone[action.type]}`}>{action.type}</span><div><p className="font-mono text-xs text-white">{action.target}</p><p className="mt-1.5 font-mono text-[10px] text-[var(--text-muted)]">{action.argument}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 font-mono text-[9px] uppercase tracking-wider text-[var(--text-muted)]"><span>Order 0{action.index}</span><span>{action.dependency}</span><span>{action.scope}</span><span>{action.requirement}</span><span className="text-[var(--safe)]">Snapshot-backed</span></div></div><div className="text-left sm:text-right"><p className="font-mono text-xs font-medium tabular-nums">{action.affectedResources}</p><p className="mt-1 text-[9px] text-[var(--text-muted)]">resources in scope</p></div>{index < planActions.length - 1 && <ChevronRight size={13} className="absolute -bottom-2.5 left-5 rotate-90 bg-[var(--surface)] text-[var(--text-muted)]" />}</div>)}</div></section>
    </div>

    <section className="surface-panel mt-4 flex flex-col gap-5 rounded-[12px] border border-white/[0.08] bg-[var(--surface)] p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="flex flex-wrap gap-6 sm:gap-10"><div><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">Estimated impact</p><p className="mt-2 text-lg font-semibold tabular-nums">{operationScenario.resources} <span className="text-xs font-normal text-[var(--text-muted)]">resources</span></p></div><div><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">Storage</p><p className="mt-2 text-lg font-semibold tabular-nums">{operationScenario.storage}</p></div><div><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">Dependencies</p><p className="mt-2 text-lg font-semibold tabular-nums">{operationScenario.dependencies} <span className="text-xs font-normal text-[var(--text-muted)]">workflows</span></p></div><div><p className="text-[9px] uppercase tracking-wider text-[var(--text-muted)]">Preliminary risk</p><p className="mt-2 flex items-center gap-1.5 text-sm font-semibold text-[var(--high-risk)]"><ShieldAlert size={15} />{operationScenario.riskLevel} · {operationScenario.riskScore}/100</p></div></div><Link href="/action-plans" className="inline-flex items-center justify-center gap-2 rounded-[7px] bg-white px-4 py-2.5 text-xs font-medium text-black transition-colors hover:bg-zinc-200">Review Execution Plan <ArrowRight size={14} /></Link></section>
  </main></AppShell>;
}
